### ISSUE TITLE
Apply Tridentnet with YOLO

### ISSUE THREAD

**Issue by LinCoce** [TuSimple/simpledet#10]
Tridentnet is a backbone, yolo is a detector.  You can apply trident block to yolo to get the best of both worlds.

_Originally posted by @RogerChern in https://github.com/TuSimple/simpledet/issues/3#issuecomment-458781006_

Thanks for your remarkable works. 
I want to make sure how to combine trident with yolo. 
Take yolov3(Darknet-53 backbone) as an example, the final 4 conv-blocks, with downsample rate 32, may be replaced with your trident blocks, and three branches may have their own yolo-head independently for different scale obj-detection. 
The original upsample operation for FPN will be canceled. And compared with original yolov3, that large objects are detected with small feature map and small objects are detected with large feature map, in this method objects of all sizes (small, medium, large) are detected with feature maps that have the same size, specifically 8x8.
Is that right?

**Comment by RogerChern** [comment]
This setting looks good to me. You're welcome to contribute this setting back to simpledet if this works.

**Comment by AlexeyAB** [comment]
@LinCoce Hi,

Did you implement Yolo v3 with Trident Blocks?

**Comment by hitle451997** [comment]
Hi, I also care about yolov3 with Trident Blocks

**Comment by dodogoffy** [comment]
Hi, I also care about yolov3 with Trident Blocks
