### ISSUE TITLE
rpn_conv_3x3_bn_beta

### ISSUE THREAD

**Issue by hitle451997** [TuSimple/simpledet#105]
File "/tmp/simpledet/core/detection_module.py", line 316, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: rpn_conv_3x3_bn_beta is not presented

please tell me the solution

**Comment by vedrusss** [comment]
+1
I've obtained the same running 
python3 detection_test.py --config config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py

**Comment by hitle451997** [comment]
I checked in arg_params and rpn_conv_3x3_bn_beta is not presented in arg_params, the model that you provided right ?
arg_params.keys()
Out[226]: dict_keys(['stage3_unit21_conv2_offset_weight', 'stage3_unit3_bn1_branch1_gamma', 'stage3_unit23_bn1_branch1_beta', 'stage3_unit18_bn2_branch2_gamma', 'stage3_unit7_bn2_branch1_beta', 'stage3_unit16_bn3_branch1_beta', 'stage3_unit11_bn1_branch1_gamma', 'stage3_unit13_bn3_branch0_gamma', 'stage3_unit10_bn2_branch2_beta', 'stage3_unit3_bn2_branch2_gamma', 'stage3_unit23_bn2_branch0_gamma', 'stage3_unit1_bn1_gamma', 'stage3_unit10_conv2_weight', 'stage3_unit19_bn1_branch2_beta', 'stage3_unit23_bn1_branch1_gamma', 'stage3_unit8_conv1_weight', 'stage3_unit5_bn1_branch0_beta', 'stage3_unit5_bn2_branch0_gamma', 'stage2_unit3_bn2_beta', 'stage3_unit16_bn1_branch2_gamma', 'stage3_unit2_bn1_branch2_beta', 'stage3_unit23_bn3_branch1_beta', 'stage3_unit18_conv2_weight', 'stage2_unit3_bn2_gamma', 'stage3_unit1_conv2_weight', 'stage3_unit19_bn1_branch2_gamma', 'stage1_unit3_conv1_weight', 'rpn_cls_logit_weight', 'stage3_unit23_bn3_branch2_gamma', 'stage3_unit10_bn2_branch0_gamma', 'stage3_unit10_conv1_weight', 'stage3_unit9_conv1_weight', 'stage3_unit18_bn3_branch2_gamma', 'stage2_unit4_bn3_beta', 'stage3_unit3_conv1_weight', 'stage3_unit19_bn3_branch1_gamma', 'stage3_unit10_bn1_branch2_gamma', 'stage3_unit13_bn1_branch0_gamma', 'stage3_unit17_bn3_branch2_gamma', 'stage3_unit3_bn1_branch0_gamma', 'stage3_unit12_bn2_branch0_beta', 'stage3_unit10_bn3_branch2_gamma', 'stage3_unit7_bn3_branch0_gamma', 'stage3_unit21_bn1_branch1_gamma', 'stage3_unit1_bn1_beta', 'stage2_unit2_bn2_beta', 'stage3_unit8_bn2_branch0_beta', 'stage3_unit12_bn3_branch0_beta', 'stage3_unit12_bn2_branch1_gamma', 'stage3_unit14_bn2_branch2_beta', 'stage3_unit19_bn3_branch2_gamma', 'stage3_unit18_bn1_branch2_beta', 'stage3_unit6_bn2_branch0_beta', 'stage3_unit8_bn2_branch1_gamma', 'stage3_unit10_bn1_branch2_beta', 'bbox_cls_logit_bias', 'stage2_unit1_conv3_weight', 'stage3_unit13_conv1_weight', 'stage3_unit16_conv3_weight', 'stage3_unit11_conv3_weight', 'stage3_unit14_bn2_branch2_gamma', 'stage3_unit16_bn1_branch1_beta', 'stage3_unit20_bn2_branch2_beta', 'stage3_unit13_bn1_branch2_beta', 'stage3_unit14_bn1_branch0_gamma', 'stage3_unit7_bn3_branch2_gamma', 'stage3_unit5_bn3_branch1_gamma', 'stage3_unit20_bn1_branch0_beta', 'stage3_unit5_bn1_branch2_beta', 'stage3_unit22_bn3_branch1_gamma', 'stage3_unit21_bn3_branch2_beta', 'stage3_unit12_bn1_branch2_gamma', 'stage2_unit4_bn1_gamma', 'stage4_unit3_bn1_gamma', 'stage4_unit3_bn2_gamma', 'stage3_unit10_bn1_branch1_beta', 'stage3_unit19_bn3_branch1_beta', 'stage3_unit14_bn1_branch2_beta', 'stage3_unit6_conv1_weight', 'stage2_unit1_sc_weight', 'stage3_unit18_bn3_branch0_beta', 'stage3_unit22_bn2_branch2_gamma', 'stage3_unit22_bn1_branch0_beta', 'stage3_unit9_conv3_weight', 'stage3_unit21_bn3_branch1_gamma', 'stage3_unit18_conv3_weight', 'stage3_unit8_conv3_weight', 'stage2_unit4_bn2_gamma', 'stage3_unit20_bn3_branch0_beta', 'stage3_unit15_bn1_branch2_beta', 'stage3_unit16_bn3_branch2_gamma', 'stage3_unit12_bn2_branch2_gamma', 'stage3_unit16_bn3_branch0_beta', 'stage3_unit20_conv1_weight', 'stage3_unit5_bn2_branch0_beta', 'stage3_unit17_bn3_branch2_beta', 'stage3_unit11_bn3_branch1_gamma', 'stage4_unit3_bn3_beta', 'stage3_unit17_bn1_branch1_beta', 'stage3_unit7_bn2_branch0_beta', 'stage3_unit9_bn3_branch0_beta', 'stage3_unit12_bn3_branch0_gamma', 'stage3_unit18_bn1_branch1_gamma', 'stage3_unit4_conv3_weight', 'stage3_unit20_conv3_weight', 'stage3_unit15_bn1_branch0_beta', 'stage3_unit14_bn1_branch1_gamma', 'stage3_unit5_conv2_weight', 'stage3_unit1_bn3_gamma', 'stage3_unit6_conv3_weight', 'stage3_unit2_bn2_branch0_gamma', 'stage3_unit20_bn3_branch0_gamma', 'stage3_unit6_bn3_branch0_beta', 'stage3_unit20_bn3_branch1_beta', 'stage3_unit19_conv3_weight', 'stage3_unit20_bn2_branch2_gamma', 'stage3_unit6_bn3_branch1_gamma', 'stage3_unit21_bn3_branch2_gamma', 'stage2_unit4_bn2_beta', 'stage1_unit2_bn2_gamma', 'stage3_unit22_bn2_branch2_beta', 'stage3_unit21_bn1_branch1_beta', 'stage3_unit12_bn1_branch0_beta', 'stage3_unit17_bn2_branch1_beta', 'stage4_unit2_bn1_gamma', 'stage3_unit5_bn1_branch2_gamma', 'stage1_unit2_bn1_gamma', 'stage3_unit8_bn1_branch1_beta', 'stage2_unit1_conv1_weight', 'stage3_unit12_conv2_weight', 'stage3_unit3_bn3_branch0_gamma', 'stage3_unit18_bn2_branch0_beta', 'stage3_unit16_bn3_branch2_beta', 'stage3_unit5_conv3_weight', 'stage3_unit11_bn3_branch2_gamma', 'stage3_unit5_bn3_branch2_beta', 'stage3_unit1_bn2_beta', 'stage3_unit12_bn1_branch2_beta', 'stage3_unit15_bn1_branch0_gamma', 'stage3_unit1_bn3_beta', 'stage3_unit10_bn2_branch2_gamma', 'bn0_beta', 'stage3_unit7_bn3_branch2_beta', 'stage1_unit1_bn1_beta', 'stage3_unit10_bn3_branch0_gamma', 'stage3_unit22_bn1_branch0_gamma', 'stage3_unit16_bn2_branch1_beta', 'stage3_unit21_conv3_weight', 'stage1_unit2_conv3_weight', 'stage3_unit8_bn2_branch1_beta', 'stage3_unit8_bn2_branch2_beta', 'stage3_unit21_bn1_branch2_gamma', 'stage3_unit2_bn2_branch2_gamma', 'stage4_unit1_bn2_beta', 'stage3_unit17_bn2_branch0_beta', 'stage3_unit4_bn3_branch1_gamma', 'stage3_unit5_bn3_branch0_gamma', 'stage3_unit22_conv1_weight', 'stage3_unit3_bn3_branch2_gamma', 'stage3_unit16_bn2_branch2_beta', 'stage3_unit11_bn3_branch0_gamma', 'stage3_unit3_bn3_branch2_beta', 'stage3_unit15_bn2_branch2_gamma', 'stage3_unit9_bn3_branch2_gamma', 'stage3_unit14_conv3_weight', 'stage3_unit11_bn3_branch0_beta', 'stage3_unit23_bn3_branch1_gamma', 'stage3_unit21_bn2_branch1_beta', 'stage3_unit18_bn3_branch1_beta', 'stage1_unit3_conv3_weight', 'stage3_unit14_bn1_branch1_beta', 'stage3_unit2_conv3_weight', 'stage3_unit9_bn2_branch0_gamma', 'stage3_unit5_bn1_branch0_gamma', 'stage3_unit23_bn2_branch2_gamma', 'stage3_unit15_conv1_weight', 'stage3_unit2_bn1_branch1_gamma', 'stage3_unit6_bn2_branch1_beta', 'stage4_unit1_conv3_weight', 'stage2_unit2_bn3_beta', 'stage3_unit12_bn1_branch1_beta', 'stage3_unit15_bn1_branch1_gamma', 'stage3_unit14_bn3_branch0_gamma', 'stage3_unit6_bn2_branch2_gamma', 'stage4_unit3_bn3_gamma', 'stage3_unit4_bn2_branch2_beta', 'stage3_unit16_bn1_branch0_gamma', 'stage1_unit3_bn2_beta', 'stage3_unit15_conv3_weight', 'stage3_unit8_bn3_branch1_gamma', 'stage3_unit9_conv2_weight', 'stage3_unit14_bn3_branch2_beta', 'stage3_unit22_bn1_branch2_gamma', 'stage3_unit7_conv1_weight', 'stage1_unit1_bn2_gamma', 'stage3_unit16_bn2_branch1_gamma', 'stage3_unit21_bn2_branch0_gamma', 'stage3_unit18_bn1_branch2_gamma', 'stage3_unit7_bn3_branch1_beta', 'stage3_unit10_bn3_branch1_beta', 'stage3_unit6_bn1_branch0_beta', 'stage3_unit22_bn1_branch2_beta', 'stage3_unit10_bn3_branch2_beta', 'stage4_unit1_bn1_beta', 'bn0_gamma', 'stage3_unit19_bn1_branch0_gamma', 'stage4_unit1_bn3_gamma', 'stage3_unit17_conv3_weight', 'stage3_unit22_bn3_branch2_gamma', 'stage3_unit18_conv1_weight', 'stage3_unit22_conv2_offset_bias', 'stage2_unit1_conv2_weight', 'stage3_unit13_bn2_branch1_gamma', 'stage3_unit2_bn3_branch0_beta', 'stage3_unit15_bn2_branch1_beta', 'stage3_unit11_conv1_weight', 'stage3_unit22_bn2_branch1_beta', 'stage3_unit14_bn1_branch2_gamma', 'stage1_unit2_conv1_weight', 'stage3_unit11_bn2_branch2_beta', 'stage3_unit17_conv2_weight', 'stage3_unit8_bn1_branch2_gamma', 'stage3_unit17_bn2_branch2_gamma', 'stage3_unit11_bn3_branch2_beta', 'stage3_unit3_bn1_branch1_beta', 'stage2_unit3_conv2_weight', 'stage3_unit19_bn2_branch1_gamma', 'stage3_unit23_conv3_weight', 'stage3_unit14_conv2_weight', 'stage3_unit1_bn2_gamma', 'stage3_unit2_bn3_branch2_beta', 'stage3_unit10_bn3_branch0_beta', 'stage3_unit2_bn3_branch1_beta', 'stage2_unit2_conv3_weight', 'stage3_unit21_bn2_branch2_gamma', 'stage2_unit4_conv1_weight', 'stage3_unit6_bn2_branch2_beta', 'stage3_unit15_bn3_branch2_beta', 'stage3_unit23_bn3_branch2_beta', 'stage3_unit20_bn2_branch1_beta', 'stage3_unit13_bn1_branch0_beta', 'stage3_unit16_bn1_branch0_beta', 'stage3_unit14_bn2_branch1_beta', 'stage3_unit15_bn2_branch1_gamma', 'stage2_unit3_conv3_weight', 'stage3_unit12_conv3_weight', 'stage3_unit12_bn3_branch2_beta', 'stage3_unit3_bn1_branch2_beta', 'stage3_unit22_conv3_weight', 'stage3_unit11_bn1_branch0_gamma', 'stage2_unit2_bn1_gamma', 'stage3_unit20_bn1_branch1_beta', 'stage3_unit4_bn1_branch1_gamma', 'stage4_unit1_conv1_weight', 'bn_data_gamma', 'stage3_unit9_bn2_branch2_beta', 'stage3_unit20_bn1_branch2_beta', 'stage3_unit18_bn2_branch1_gamma', 'stage3_unit3_bn2_branch0_gamma', 'stage3_unit16_bn2_branch0_beta', 'stage3_unit18_bn1_branch0_gamma', 'stage2_unit4_conv2_weight', 'stage3_unit15_bn2_branch0_gamma', 'stage4_unit2_conv2_weight', 'stage3_unit20_bn2_branch0_beta', 'stage3_unit23_bn2_branch2_beta', 'stage4_unit2_bn2_beta', 'stage3_unit4_bn2_branch1_gamma', 'bn1_beta', 'stage3_unit20_bn1_branch1_gamma', 'stage3_unit7_bn2_branch2_beta', 'stage3_unit7_bn1_branch2_beta', 'stage1_unit3_bn3_gamma', 'stage2_unit2_bn3_gamma', 'stage3_unit2_bn1_branch0_gamma', 'stage4_unit3_bn1_beta', 'stage3_unit4_bn1_branch0_beta', 'stage3_unit11_bn2_branch0_gamma', 'stage3_unit19_bn1_branch1_beta', 'stage3_unit8_bn1_branch0_beta', 'stage3_unit2_bn3_branch2_gamma', 'stage3_unit8_bn1_branch0_gamma', 'stage3_unit9_bn2_branch1_gamma', 'stage3_unit12_bn2_branch1_beta', 'stage4_unit1_sc_weight', 'stage3_unit12_bn3_branch2_gamma', 'stage1_unit1_conv3_weight', 'stage3_unit17_bn1_branch0_beta', 'stage3_unit4_bn1_branch2_beta', 'stage3_unit6_conv2_weight', 'stage3_unit13_bn3_branch1_beta', 'stage2_unit3_conv1_weight', 'stage3_unit9_bn2_branch2_gamma', 'stage3_unit14_bn3_branch1_beta', 'stage3_unit11_bn2_branch2_gamma', 'stage4_unit1_bn3_beta', 'stage2_unit1_bn2_beta', 'stage3_unit12_bn1_branch0_gamma', 'stage3_unit15_bn3_branch2_gamma', 'stage3_unit19_conv1_weight', 'stage3_unit10_bn1_branch1_gamma', 'stage3_unit19_bn3_branch0_beta', 'stage3_unit13_bn2_branch0_beta', 'stage3_unit6_bn2_branch0_gamma', 'stage3_unit22_bn3_branch0_gamma', 'stage3_unit16_bn3_branch1_gamma', 'stage3_unit23_bn1_branch2_beta', 'stage3_unit14_bn3_branch0_beta', 'stage3_unit11_bn1_branch2_gamma', 'stage3_unit9_bn1_branch2_beta', 'stage2_unit3_bn3_gamma', 'stage1_unit1_sc_weight', 'stage2_unit1_bn2_gamma', 'stage3_unit21_bn3_branch1_beta', 'stage3_unit3_conv3_weight', 'stage3_unit4_bn3_branch0_beta', 'stage3_unit18_bn2_branch0_gamma', 'stage3_unit19_bn1_branch0_beta', 'stage3_unit23_bn3_branch0_beta', 'stage3_unit11_bn2_branch1_beta', 'stage3_unit20_bn1_branch0_gamma', 'stage1_unit3_bn3_beta', 'rpn_conv_3x3_weight', 'stage3_unit13_bn2_branch0_gamma', 'stage3_unit10_bn2_branch0_beta', 'stage3_unit3_bn2_branch2_beta', 'stage3_unit6_bn3_branch2_gamma', 'stage3_unit11_conv2_weight', 'stage3_unit9_bn1_branch0_beta', 'stage3_unit8_bn1_branch2_beta', 'bn_data_beta', 'stage4_unit2_conv1_weight', 'stage3_unit8_bn3_branch0_beta', 'stage3_unit8_bn2_branch0_gamma', 'stage3_unit8_conv2_weight', 'stage3_unit23_conv2_weight', 'stage3_unit9_bn3_branch0_gamma', 'stage3_unit23_conv2_offset_weight', 'stage3_unit6_bn1_branch1_beta', 'stage3_unit1_sc_weight', 'stage3_unit2_bn1_branch0_beta', 'stage3_unit8_bn3_branch2_gamma', 'stage1_unit2_conv2_weight', 'stage3_unit19_bn3_branch2_beta', 'stage3_unit14_bn2_branch0_beta', 'stage3_unit17_bn1_branch2_beta', 'stage3_unit22_bn3_branch2_beta', 'stage3_unit2_bn3_branch0_gamma', 'stage2_unit1_bn1_gamma', 'stage3_unit7_bn1_branch2_gamma', 'stage3_unit2_bn2_branch2_beta', 'stage3_unit10_bn1_branch0_gamma', 'stage1_unit1_conv2_weight', 'stage3_unit4_bn3_branch1_beta', 'stage3_unit4_bn2_branch2_gamma', 'stage3_unit5_bn1_branch1_gamma', 'stage3_unit10_bn2_branch1_beta', 'stage3_unit8_bn2_branch2_gamma', 'stage2_unit3_bn1_beta', 'stage3_unit11_bn1_branch0_beta', 'stage3_unit7_conv2_weight', 'stage3_unit7_bn3_branch0_beta', 'stage4_unit2_bn2_gamma', 'stage3_unit17_bn3_branch1_gamma', 'stage3_unit19_bn1_branch1_gamma', 'stage3_unit9_bn3_branch2_beta', 'stage3_unit2_bn2_branch1_gamma', 'stage2_unit2_bn2_gamma', 'stage3_unit20_bn2_branch0_gamma', 'stage3_unit22_conv2_weight', 'stage3_unit8_bn3_branch2_beta', 'stage3_unit5_bn2_branch1_gamma', 'stage3_unit2_bn2_branch1_beta', 'stage3_unit14_bn2_branch1_gamma', 'stage3_unit4_conv1_weight', 'stage3_unit18_bn1_branch0_beta', 'stage3_unit15_bn1_branch1_beta', 'stage3_unit2_bn1_branch1_beta', 'stage3_unit4_bn1_branch1_beta', 'stage3_unit21_bn3_branch0_gamma', 'stage3_unit14_bn3_branch2_gamma', 'stage3_unit3_bn2_branch1_beta', 'stage3_unit23_bn1_branch0_gamma', 'stage2_unit1_bn3_gamma', 'stage3_unit18_bn3_branch0_gamma', 'stage3_unit19_bn2_branch2_gamma', 'stage3_unit13_bn1_branch2_gamma', 'stage3_unit6_bn1_branch2_beta', 'stage3_unit16_bn1_branch1_gamma', 'stage3_unit9_bn1_branch2_gamma', 'stage3_unit4_bn3_branch2_beta', 'stage3_unit14_conv1_weight', 'stage3_unit21_bn1_branch0_gamma', 'stage2_unit3_bn1_gamma', 'stage2_unit4_conv3_weight', 'stage3_unit8_bn3_branch1_beta', 'stage3_unit17_bn2_branch0_gamma', 'stage1_unit1_bn1_gamma', 'stage3_unit16_bn2_branch2_gamma', 'stage3_unit15_bn2_branch0_beta', 'stage3_unit22_bn3_branch1_beta', 'stage1_unit2_bn3_gamma', 'stage3_unit21_bn1_branch2_beta', 'stage3_unit6_bn3_branch0_gamma', 'stage1_unit2_bn2_beta', 'stage1_unit1_bn3_beta', 'stage2_unit2_bn1_beta', 'stage3_unit22_bn3_branch0_beta', 'stage3_unit21_bn3_branch0_beta', 'stage4_unit3_conv1_weight', 'stage1_unit2_bn3_beta', 'stage3_unit7_bn3_branch1_gamma', 'stage3_unit23_bn3_branch0_gamma', 'stage3_unit19_bn3_branch0_gamma', 'stage4_unit3_conv3_weight', 'stage3_unit22_bn2_branch0_gamma', 'stage1_unit1_bn2_beta', 'stage1_unit1_bn3_gamma', 'stage3_unit23_bn1_branch0_beta', 'stage3_unit14_bn2_branch0_gamma', 'stage3_unit12_conv1_weight', 'stage1_unit3_bn2_gamma', 'stage3_unit4_bn1_branch2_gamma', 'stage3_unit5_bn3_branch2_gamma', 'stage3_unit11_bn1_branch1_beta', 'stage3_unit5_bn3_branch1_beta', 'stage3_unit5_bn2_branch2_gamma', 'stage3_unit1_conv3_weight', 'stage3_unit23_bn1_branch2_gamma', 'stage3_unit13_bn3_branch2_beta', 'stage3_unit16_conv2_weight', 'stage3_unit16_bn2_branch0_gamma', 'stage3_unit15_bn2_branch2_beta', 'stage3_unit19_bn2_branch0_beta', 'stage3_unit11_bn2_branch0_beta', 'stage3_unit18_bn3_branch1_gamma', 'stage3_unit13_bn2_branch1_beta', 'stage3_unit7_bn1_branch0_gamma', 'stage4_unit2_conv3_weight', 'bn1_gamma', 'stage3_unit17_bn1_branch1_gamma', 'stage3_unit12_bn3_branch1_beta', 'stage2_unit4_bn3_gamma', 'stage3_unit9_bn3_branch1_beta', 'stage3_unit5_bn2_branch1_beta', 'stage3_unit21_conv1_weight', 'stage3_unit3_bn3_branch0_beta', 'stage3_unit3_bn3_branch1_beta', 'stage3_unit18_bn2_branch2_beta', 'stage3_unit12_bn2_branch0_gamma', 'stage3_unit19_bn2_branch2_beta', 'stage3_unit20_bn3_branch2_beta', 'stage3_unit5_conv1_weight', 'stage3_unit20_conv2_weight', 'stage3_unit5_bn3_branch0_beta', 'stage3_unit8_bn3_branch0_gamma', 'stage3_unit6_bn3_branch1_beta', 'stage3_unit10_bn1_branch0_beta', 'stage3_unit17_bn2_branch2_beta', 'stage3_unit17_bn3_branch0_beta', 'stage3_unit9_bn3_branch1_gamma', 'stage3_unit9_bn2_branch1_beta', 'stage3_unit6_bn1_branch1_gamma', 'stage3_unit16_bn3_branch0_gamma', 'stage4_unit3_bn2_beta', 'stage3_unit20_bn3_branch2_gamma', 'stage3_unit13_bn1_branch1_gamma', 'stage3_unit18_bn1_branch1_beta', 'bbox_reg_delta_weight', 'stage3_unit15_bn3_branch0_gamma', 'stage3_unit15_bn3_branch1_beta', 'stage3_unit19_conv2_weight', 'stage3_unit15_conv2_weight', 'stage3_unit13_conv3_weight', 'stage3_unit7_bn2_branch1_gamma', 'stage3_unit23_bn2_branch1_beta', 'rpn_bbox_delta_bias', 'stage2_unit1_bn3_beta', 'stage3_unit4_bn3_branch0_gamma', 'stage2_unit4_bn1_beta', 'stage3_unit14_bn1_branch0_beta', 'stage3_unit17_bn1_branch2_gamma', 'stage3_unit18_bn2_branch1_beta', 'stage3_unit22_conv2_offset_weight', 'stage3_unit3_bn3_branch1_gamma', 'stage4_unit2_bn3_gamma', 'stage3_unit2_bn2_branch0_beta', 'stage3_unit22_bn2_branch0_beta', 'stage3_unit17_bn2_branch1_gamma', 'stage3_unit15_bn3_branch1_gamma', 'stage3_unit2_conv1_weight', 'stage3_unit10_bn2_branch1_gamma', 'stage3_unit6_bn3_branch2_beta', 'stage3_unit19_bn2_branch1_beta', 'stage3_unit4_conv2_weight', 'rpn_conv_3x3_bias', 'stage4_unit1_bn1_gamma', 'stage4_unit2_bn3_beta', 'stage1_unit1_conv1_weight', 'stage4_unit1_conv2_weight', 'stage3_unit11_bn2_branch1_gamma', 'stage3_unit22_bn2_branch1_gamma', 'stage3_unit20_bn3_branch1_gamma', 'bbox_reg_delta_bias', 'stage3_unit21_bn2_branch0_beta', 'stage3_unit13_bn3_branch1_gamma', 'stage3_unit9_bn1_branch0_gamma', 'stage4_unit2_bn1_beta', 'stage3_unit18_bn3_branch2_beta', 'stage3_unit3_bn2_branch1_gamma', 'stage3_unit9_bn1_branch1_beta', 'conv0_weight', 'stage3_unit13_conv2_weight', 'stage3_unit15_bn3_branch0_beta', 'stage3_unit3_bn1_branch0_beta', 'stage3_unit16_conv1_weight', 'stage3_unit12_bn2_branch2_beta', 'stage3_unit7_bn2_branch2_gamma', 'stage3_unit7_bn1_branch1_gamma', 'stage3_unit17_bn3_branch1_beta', 'stage3_unit17_conv1_weight', 'stage3_unit12_bn1_branch1_gamma', 'rpn_bbox_delta_weight', 'stage1_unit3_conv2_weight', 'bbox_cls_logit_weight', 'stage3_unit15_bn1_branch2_gamma', 'stage3_unit7_bn1_branch1_beta', 'stage3_unit5_bn1_branch1_beta', 'stage3_unit9_bn2_branch0_beta', 'stage3_unit13_bn3_branch0_beta', 'stage3_unit6_bn1_branch0_gamma', 'stage3_unit7_bn2_branch0_gamma', 'stage3_unit2_conv2_weight', 'stage3_unit8_bn1_branch1_gamma', 'rpn_cls_logit_bias', 'stage3_unit7_conv3_weight', 'stage3_unit23_conv1_weight', 'stage3_unit21_bn1_branch0_beta', 'stage3_unit4_bn3_branch2_gamma', 'stage3_unit21_conv2_offset_bias', 'stage2_unit2_conv2_weight', 'stage3_unit21_bn2_branch1_gamma', 'stage3_unit4_bn2_branch1_beta', 'stage3_unit20_bn2_branch1_gamma', 'stage3_unit13_bn2_branch2_gamma', 'stage3_unit12_bn3_branch1_gamma', 'stage3_unit13_bn1_branch1_beta', 'stage3_unit13_bn3_branch2_gamma', 'stage3_unit22_bn1_branch1_beta', 'stage3_unit1_conv1_weight', 'stage3_unit5_bn2_branch2_beta', 'stage3_unit2_bn3_branch1_gamma', 'stage3_unit4_bn1_branch0_gamma', 'stage2_unit3_bn3_beta', 'stage3_unit22_bn1_branch1_gamma', 'stage3_unit2_bn1_branch2_gamma', 'stage3_unit23_bn2_branch0_beta', 'stage3_unit7_bn1_branch0_beta', 'stage3_unit6_bn1_branch2_gamma', 'stage1_unit2_bn1_beta', 'stage3_unit11_bn1_branch2_beta', 'stage3_unit9_bn1_branch1_gamma', 'stage3_unit11_bn3_branch1_beta', 'stage3_unit6_bn2_branch1_gamma', 'stage3_unit17_bn3_branch0_gamma', 'stage3_unit21_conv2_weight', 'stage3_unit10_conv3_weight', 'stage3_unit14_bn3_branch1_gamma', 'stage3_unit16_bn1_branch2_beta', 'stage4_unit3_conv2_weight', 'stage3_unit3_bn1_branch2_gamma', 'stage3_unit10_bn3_branch1_gamma', 'stage1_unit3_bn1_beta', 'stage3_unit19_bn2_branch0_gamma', 'stage3_unit13_bn2_branch2_beta', 'stage3_unit21_bn2_branch2_beta', 'stage3_unit23_bn2_branch1_gamma', 'stage4_unit1_bn2_gamma', 'stage2_unit1_bn1_beta', 'stage3_unit17_bn1_branch0_gamma', 'stage1_unit3_bn1_gamma', 'stage3_unit4_bn2_branch0_gamma', 'stage3_unit3_conv2_weight', 'stage2_unit2_conv1_weight', 'stage3_unit4_bn2_branch0_beta', 'stage3_unit23_conv2_offset_bias', 'stage3_unit3_bn2_branch0_beta', 'stage3_unit20_bn1_branch2_gamma'])

**Comment by RogerChern** [comment]
Could you please specify which config you are using and include the complete error output?

**Comment by RogerChern** [comment]
Sorry, I got the cause of this. Old models do not have BN for rpn head. A fast workaround could be changing the NormalizeParam as `normalizer = normalizer_factory(type="fixbn")` for test. We shall deal with this. 
@hitle451997  @vedrusss

**Comment by RogerChern** [comment]
Fixed in #107
