### ISSUE TITLE
ask for way to fine-tune on my own dataset and testing

### ISSUE THREAD

**Issue by anxu829** [TuSimple/simpledet#11]
Hi , i am a freshman in object detection.  I noticed that you publish a tutorial for training on coco dataset. and i am wondering if there is way that I can finetune on my own dataset with pretrained imagenet/coco model ? and another question is that is there a tutorial for us to infer/test on an new single image for deployment ?

**Comment by winstywang** [comment]
You can convert your data into COCO data format. That is the easiest way to train on own dataset. The focus of this work is not fast deployment, so we only provide a fast batch inference script. If you are interested in deployment, you may need to refer to library such as TensorRT.

**Comment by RogerChern** [comment]
You can also directly create the roidb used in training following the data structure in [Preparing Data](https://github.com/TuSimple/simpledet#preparing-data). Please refer to [generate_roidb.py](https://github.com/TuSimple/simpledet/blob/master/utils/generate_roidb.py) for implementation details.
