### ISSUE TITLE
How to save checkpoint before one epoch finish?

### ISSUE THREAD

**Issue by zekun-li** [TuSimple/simpledet#114]
Is there any place to change the epoch_size parameter? Or should I use batch_end_callback function to do_checkpoint?

**Comment by RogerChern** [comment]
This is not easy for the current DetModule. Trying to hack the data loader to raise IterationStop before a real epoch ends.

**Comment by zekun-li** [comment]
Thanks! I was able to achieve this by following jonbakerfish's answer in this thread https://github.com/apache/incubator-mxnet/issues/658
