### ISSUE TITLE
FP16 training speed

### ISSUE THREAD

**Issue by Retiina** [TuSimple/simpledet#124]
Thanks for you excellent job. I am training `mask_r50v1_fpn_1x.py` on **8-v100** in **FP16** mode, but the speed is similar to **FP32**, is this normal? I only change `general.fp16=True` . Here is the training screenshot:

Memory are reported by `nvidia-smi`, use smallest memory

FP32, memory is **6.7GB**

<img width="962" alt="Screen Shot 2019-06-11 at 1 33 29 PM" src="https://user-images.githubusercontent.com/49137956/59246007-8304a180-8c4d-11e9-92ce-92d43ffca29a.png">

FP16, memory is **5.5GB**

<img width="957" alt="Screen Shot 2019-06-11 at 1 37 53 PM" src="https://user-images.githubusercontent.com/49137956/59246173-1fc73f00-8c4e-11e9-8f26-0c0f7d372c5c.png">

My environment is as follow: 8 v100s, cuda 9, cudnn 7.0.4, nvidia-drive 390.3. Could you give me some advice, thanks in advance!

**Comment by huangzehao** [comment]
The training speed is not only depends on GPU computation, but also CPU computation and data loading.
For fpn based mask-rcnn, there are several python operators which are not very efficient. Also, the performance of data loading will influence the training speed.

A simple method to benchmark network speed is using a fake loader. 
https://github.com/TuSimple/simpledet/blob/master/core/detection_input.py#L635
Here is an exmaple for fake loader:


    def next(self):
        if self.iter_next():
            if self.result is not None:
                result = self.load_batch()
                self.data = result.data
                self.label = result.label
                self.result = result
            else:
                return self.result
            return result

**Comment by Retiina** [comment]
Thanks for your reply! Have you benchmark fpn based mask-rcnn fp16 training, what is the speed and memory usage under fp32 and fp16 mode?

In FP16 Benchmark and simpledet paper, FP16 training speed is significantly faster than FP32. So the training speed is not exactly the "training speed" appeared in the log, am I right?

If this is the case, I am curious about the way to measure the training speed, could you give me more detailed instruction to measure training speed, really thanks about that!

**Comment by RogerChern** [comment]
The speedup ratio varies between different models. 
Mask R-CNN is quite complicated a model comprising of a lot of python-written operators. 
FP16 only accelerates convolutions and batchnorms. 
The reported training speeup is measured on Faster R-CNN.  
For Mask R-CNN, we shall look into the bottleneck which slows it down.
