### ISSUE TITLE
Question: RpnHead training with fp16

### ISSUE THREAD

**Issue by suyz526** [TuSimple/simpledet#128]
Hi,

in RpnHead's `get_output()`, the data type has already transformed from fp16 to fp32. And in its 'get_loss()', it still has a `scale_loss_shift = 128.0`. Is the `scale_loss_shift` here necessary ?

**Comment by RogerChern** [comment]
Necessary. Scale loss is meant to simulate bfloat16. Check [Mixed Precision Training](https://arxiv.org/abs/1710.03740) for more details.
