### ISSUE TITLE
shape do not match total elements

### ISSUE THREAD

**Issue by w11m** [TuSimple/simpledet#143]
i want to train coco dataset on tridentnet, and i use this detection config "tridentnet_r50v1c4_c5_1x.py", but i got an error like this:

File "/usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:25:53] include/mxnet/././tensor_blob.h:290: Check failed: this->shape_.Size() == static_cast<size_t>(shape.Size()) (6 vs. 12) : TBlob.get_with_shape: new and old shape do not match total elements
Stack trace:
  [bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7f9ce3bb7a72]
  [bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mshadow::Tensor<mshadow::gpu, 2, float> mxnet::TBlob::get_with_shape<mshadow::gpu, 2, float>(mshadow::Shape<2> const&, mshadow::Stream<mshadow::gpu>*) const+0x21c) [0x7f9ce57d141c]
  [bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::ProposalTargetOp_v2<mshadow::gpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x684) [0x7f9ce59b5f44]
  [bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0xa81) [0x7f9ce54dad51]
  [bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x76) [0x7f9ce5c62ee6]
  [bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(+0x30d2a67) [0x7f9ce5c2ca67]
  [bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x995) [0x7f9ce5b6c485]
  [bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0x11d) [0x7f9ce5b84e8d]
  [bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#4}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>&&)+0x4e) [0x7f9ce5b8513e]

**Comment by RogerChern** [comment]
Sorry, we could not reproduce this error. Could you please provide more information about your experiment environment.

**Comment by w11m** [comment]
pip3 version

```
Package             Version  
------------------- ---------
absl-py             0.7.1    
astor               0.8.0    
certifi             2019.6.16
chardet             3.0.4    
cycler              0.10.0   
Cython              0.29.11  
gast                0.2.2    
graphviz            0.8.4    
grpcio              1.21.1   
h5py                2.9.0    
idna                2.8      
Keras               2.2.4    
Keras-Applications  1.0.8    
Keras-Preprocessing 1.1.0    
kiwisolver          1.1.0    
Markdown            3.1.1    
matplotlib          3.0.3    
mxnet               1.5.0    
numpy               1.16.4   
opencv-python       4.1.0.25 
pip                 19.1.1   
protobuf            3.8.0    
pycocotools         2.0      
pyparsing           2.4.0    
python-dateutil     2.8.0    
pytz                2019.1   
PyYAML              5.1.1    
requests            2.22.0   
scipy               1.3.0    
setuptools          39.1.0   
six                 1.12.0   
tensorboard         1.9.0    
tensorflow-gpu      1.9.0    
termcolor           1.1.0    
urllib3             1.25.3   
Werkzeug            0.15.4   
wheel               0.29.0  
```
Ubuntu version
```
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
```
Linux kernel version
`4.15.0-50-generic`

GCC version
`5.4.0`

nvcc version
`V9.0.176`

cudnn version
`7.6.0`

nccl version
`2.4.2`

**Comment by RogerChern** [comment]
Hi @w11m. 
Your environment looks fine to me. Could you please try out the docker image provided in [INSTALL.md](https://github.com/TuSimple/simpledet/blob/master/doc/INSTALL.md) to see if this problem persists.

**Comment by w11m** [comment]
@RogerChern thanks i will try to test the environment through docker

**Comment by w11m** [comment]
Sorry @RogerChern  did you put the mxnet in the image? it shows no module named mxnet

**Comment by RogerChern** [comment]
Weird problem. Maybe the `mxnext` package is missing? You can get it from `git clone https://github.com/RogerChern/mxnext`

**Comment by w11m** [comment]
i mean 'mxnet' not 'mxnext'

**Comment by RogerChern** [comment]
You should be able to import `mxnet` inside the container after executing `nvidia-docker run -it rogerchen/simpledet:cuda9 zsh`.
May you are using another shell instead of `zsh`. Currently, we are using `pyenv` as our python version manager. And it only patches zsh runtime for now.

**Comment by RogerChern** [comment]
Could you please give the output of `docker run -it --rm rogerchen/simpledet:cuda9 zsh -ic "python -c 'import mxnet as mx; print(mx.__file__)'"` on your machine?

**Comment by w11m** [comment]
@RogerChern there is no problem with the `docker` 
the error `(mxnet)` happened because we forget using the `zsh`

**Comment by w11m** [comment]
But still an `cudaMalloc failed: out of memory` error
we already change the config.py 
```
    class KvstoreParam:
        kvstore     = "local"
        batch_image = General.batch_image
        gpus        = [0]
        fp16        = General.fp16
```

our training environment is based on 1 v-100 32G is that possible ?

**Comment by RogerChern** [comment]
Hi @w11m,
This is quite strange since `tridentnet_r50v1c4_c5_1x.py` consumes about 6.2G GPU MEM. 
Is the OOM issue specific to `tridentnet_r50v1c4_c5_1x.py`?
Could you please kindly try some other configs to see if this persist.

And for V100, the cuda10 runtime is recommended.
`nvidia-docker run -it rogerchen/simpledet:cuda10 zsh`

**Comment by w11m** [comment]
i choose another config 'tridentnet_r101v1c4_c5_1x.py', but still OOM, can you tell me which config i can choose?
And also  i already use cuda10.

**Comment by RogerChern** [comment]
Could you please kindly try out `faster_r50v1c4_c5_512roi_1x.py`.

**Comment by RogerChern** [comment]
Close due to no further info.
