### ISSUE TITLE
pre-trained object detection models?

### ISSUE THREAD

**Issue by mosheliv** [TuSimple/simpledet#149]
I couldn't find any pre-trained models (the experiments directory). are they available or do I have to start from scratch?

**Comment by xchani** [comment]
Check [MODEL_ZOO](https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md).

**Comment by mosheliv** [comment]
I did. I can only see links to the imagenet trained classifiers.

**Comment by mosheliv** [comment]
Oh sorry, it was a problem with my browser - the last column was cut off.
Thank you!
