### ISSUE TITLE
Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal

### ISSUE THREAD

**Issue by Kongsea** [TuSimple/simpledet#15]
When I set `gpus` to a list not starting from 0 in config:

```
class KvstoreParam:
        kvstore     = "local"
        batch_image = General.batch_image
        gpus        = [0, 1, 2, 3, 4, 5, 6, 7]
        fp16        = General.fp16
```

for example, if I set it to [1], [2, 3] or others, it raised this error while trainning:

**Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal**

Could you please help to fix it? Thank you.

> 02-03 11:03:56 lr 0.01125, lr_iters [320000, 426666]
> 02-03 11:03:56 warmup lr 0.0, warmup step 5333
> Traceback (most recent call last):
>   File "/home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/symbol/symbol.py", line 1522, in simple_bind
>     ctypes.byref(exe_handle)))
>   File "/home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/base.py", line 251, in check_call
>     raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: [18:04:07] src/storage/storage.cc:65: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal
> 
> Stack trace returned 10 entries:
> [bt] (0) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5b) [0x7fdc758f9adb]
> [bt] (1) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7fdc758fa648]
> [bt] (2) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::StorageImpl::ActivateDevice(mxnet::Context)+0x5f) [0x7fdc77e7639f]
> [bt] (3) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::StorageImpl::Alloc(mxnet::Storage::Handle*)+0x50) [0x7fdc77e718f0]
> [bt] (4) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::common::InitZeros(mxnet::NDArrayStorageType, nnvm::TShape const&, mxnet::Context const&, int)+0x73f) [0x7fdc77f0020f]
> [bt] (5) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::common::ReshapeOrCreate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nnvm::TShape const&, int, mxnet::NDArrayStorageType, mxnet::Context const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::NDArray> > >*, bool)+0xa26) [0x7fdc77f093a6]
> [bt] (6) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::InitArguments(nnvm::IndexedGraph const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, mxnet::Executor const*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::NDArray> > >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*)+0xd47) [0x7fdc77ef1ff7]
> [bt] (7) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::Context, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nnvm::TShape, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nnvm::TShape> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::NDArray> > >*, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0xa6b) [0x7fdc77efc94b]
> [bt] (8) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::Executor::SimpleBind(nnvm::Symbol, mxnet::Context const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::Context, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nnvm::TShape, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nnvm::TShape> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::NDArray> > >*, mxnet::Executor*)+0x169) [0x7fdc77efd099]
> [bt] (9) /home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(MXExecutorSimpleBind+0x2c99) [0x7fdc77e85559]
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "detection_train.py", line 226, in <module>
>     train_net(parse_args())
>   File "detection_train.py", line 209, in train_net
>     num_epoch=end_epoch
>   File "/data/simple/simpledet/core/detection_module.py", line 959, in fit
>     for_training=True, force_rebind=force_rebind)
>   File "/data/simple/simpledet/core/detection_module.py", line 440, in bind
>     state_names=self._state_names)
>   File "/home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/module/executor_group.py", line 279, in __init__
>     self.bind_exec(data_shapes, label_shapes, shared_group)
>   File "/home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/module/executor_group.py", line 375, in bind_exec
>     shared_group))
>   File "/home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
>     shared_buffer=shared_data_arrays, **input_shapes)
>   File "/home/simple/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/symbol/symbol.py", line 1528, in simple_bind
>     raise RuntimeError(error_msg)
> RuntimeError: simple_bind error. Arguments:
> data: (3, 3, 800, 1200)
> im_info: (3, 3)
> gt_bbox: (3, 300, 5)
> valid_ranges: (3, 3, 2)
> rpn_cls_label: (3, 3, 56250)
> rpn_reg_target: (3, 3, 60, 50, 75)
> rpn_reg_weight: (3, 3, 60, 50, 75)
> [11:04:07] src/storage/storage.cc:65: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: invalid device ordinal

**Comment by Kongsea** [comment]
I have set `gpus` according to my system correctly.
For example, I have 4 1080 Ti GPUs in all and the No. 0 was used by other programs. If I set `gpus` to [2, 3] or [1], it will raise the error mentioned before.

**Comment by Kongsea** [comment]
First `singularity shell simpledet.img` to shell into the image, and then run
`python3 detection_train.py --config config/faster_r101v2c4_c5_256roi_syncbn_1x.py`
in the image, it raised the following error:

> Traceback (most recent call last):
>   File "detection_train.py", line 5, in <module>
>     import numpy as np
> ImportError: No module named 'numpy'

The numpy module has not been installed in this image?
@RogerChern Thank you.

**Comment by Kongsea** [comment]
As to my platform, it has 4 1080Ti GPUs, and I use anaconda2 to organize my enviroments.
The installed modules in my environment is as follows:

> # packages in environment at /home/simple/anaconda2/envs/py3:
> #
> # Name                    Version                   Build  Channel
> absl-py                   0.6.1                    py36_0  
> blas                      1.0                         mkl  
> bleach                    1.5.0                    py36_0  
> ca-certificates           2018.03.07                    0  
> certifi                   2018.10.15               py36_0  
> chardet                   3.0.4                     <pip>
> cloudpickle               0.6.1                     <pip>
> cudatoolkit               9.0                  h13b8566_0  
> cudnn                     7.1.2                 cuda9.0_0  
> cupti                     9.0.176                       0  
> cycler                    0.10.0                    <pip>
> Cython                    0.29.3                    <pip>
> dask                      1.0.0                     <pip>
> decorator                 4.3.0                     <pip>
> graphviz                  0.8.4                     <pip>
> h5py                      2.8.0                     <pip>
> html5lib                  0.9999999                py36_0  
> idna                      2.6                       <pip>
> imageio                   2.4.1                     <pip>
> imgaug                    0.2.7                     <pip>
> intel-openmp              2019.1                      144  
> Keras                     2.2.4                     <pip>
> Keras-Applications        1.0.6                     <pip>
> Keras-Preprocessing       1.0.5                     <pip>
> kiwisolver                1.0.1                     <pip>
> libedit                   3.1.20170329         h6b74fdf_2  
> libffi                    3.2.1                hd88cf55_4  
> libgcc-ng                 8.2.0                hdf63c60_1  
> libgfortran-ng            7.3.0                hdf63c60_0  
> libprotobuf               3.6.1                hd408876_0  
> libstdcxx-ng              8.2.0                hdf63c60_1  
> markdown                  3.0.1                    py36_0  
> matplotlib                3.0.2                     <pip>
> mkl                       2018.0.3                      1  
> mkl_fft                   1.0.6            py36h7dd41cf_0  
> mkl_random                1.0.1            py36h4414c95_1  
> mxnet                     1.3.1                     <pip>
> ncurses                   6.1                  hf484d3e_0  
> networkx                  2.2                       <pip>
> numpy                     1.15.4           py36h1d66e8a_0  
> numpy                     1.15.0                    <pip>
> numpy-base                1.15.4           py36h81de0dd_0  
> opencv-python             4.0.0.21                  <pip>
> openssl                   1.1.1a               h7b6447c_0  
> Pillow                    5.3.0                     <pip>
> pip                       18.1                     py36_0  
> protobuf                  3.6.1            py36he6710b0_0  
> pycocotools               2.0                       <pip>
> pyparsing                 2.3.0                     <pip>
> pypinyin                  0.33.2                    <pip>
> python                    3.6.7                h0371630_0  
> python-dateutil           2.7.5                     <pip>
> python-speech-features    0.6                       <pip>
> pytz                      2018.9                    <pip>
> PyWavelets                1.0.1                     <pip>
> PyYAML                    3.13                      <pip>
> readline                  7.0                  h7b6447c_5  
> regex                     2018.11.22                <pip>
> requests                  2.18.4                    <pip>
> scikit-image              0.14.1                    <pip>
> scipy                     1.1.0                     <pip>
> setuptools                40.6.2                   py36_0  
> Shapely                   1.6.4.post2               <pip>
> six                       1.11.0                   py36_1  
> sqlite                    3.25.3               h7b6447c_0  
> tensorflow-gpu            1.5.0                         0  
> tensorflow-gpu-base       1.5.0            py36h8a131e3_0  
> tensorflow-tensorboard    1.5.1            py36hf484d3e_1  
> tk                        8.6.8                hbc83047_0  
> toolz                     0.9.0                     <pip>
> tqdm                      4.28.1                    <pip>
> urllib3                   1.22                      <pip>
> werkzeug                  0.14.1                   py36_0  
> wheel                     0.32.3                   py36_0  
> xz                        5.2.4                h14c3975_4  
> zlib                      1.2.11               h7b6447c_3

mxnet was installed according to instructions of this repository.
Could you help to find the problem and fix it? Thank you. @RogerChern

**Comment by RogerChern** [comment]
Please invoke singularity shell as mentioned in Setup with `sudo singularity shell --no-home --nv -s /usr/bin/zsh --bind $SIMPLEDET_WORKDIR /path/to/simpledet.img`

**Comment by RogerChern** [comment]
@Kongsea We now also provide a pre-built docker image, please contact us if this problem consists.

**Comment by Kongsea** [comment]
@RogerChern I have invoke singularity using `sudo singularity shell --no-home --nv -s /usr/bin/zsh --bind $SIMPLEDET_WORKDIR /path/to/simpledet.img` following the instructions, it raised the following warning:

> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> awk: warning: escape sequence `\.' treated as plain `.'
> Singularity: Invoking an interactive shell within container...

and it also raised the error:

> ImportError: No module named 'numpy'

I found there is not a `zsh` under `/usr/bin`, so I use `/usr/bin/bash` instead. It did not raised the warning again. But it continued to raise the error.

**Comment by RogerChern** [comment]
@Kongsea 
This is kind of wired. A known bug of singularity is that you can not invoke it in the `/root` directory. If this does not solve your problem, please consider the pre-built docker image instead.

**Comment by Kongsea** [comment]
@RogerChern Thank you. Could you please tell me where can I find the image?

**Comment by RogerChern** [comment]
It could be found in the recently updated [INSTALL.md](https://github.com/TuSimple/simpledet/blob/master/doc/INSTALL.md#setup-with-docker)

**Comment by Kongsea** [comment]
OK, thank you.

**Comment by Kongsea** [comment]
@RogerChern 
First, what should $HOST-SIMPLEDET-DIR and $CONTAINER-WORKDIR refer to? Refer to /home/simple/simpledet?
`nvidia-docker run -it -v $HOST-SIMPLEDET-DIR:$CONTAINER-WORKDIR rogerchen/simpledet /usr/bin/zsh`
Second, if there is not a `zsh` uder `/usr/bin`, what should I use?
Thank you.

**Comment by xchani** [comment]
1. ```HOST-SIMPLEDET-DIR``` and ```CONTAINER-WORKDIR``` refer to the simpledet directory in your host, and the path where the directory is mounted in container. You can check [Docker docs](https://docs.docker.com/storage/bind-mounts/) for more information.
2. ```zsh``` is installed in the provided docker image.

**Comment by Kongsea** [comment]
I got it. Thank you.

**Comment by imyhxy** [comment]
> @Kongsea We now also provide a pre-built docker image, please contact us if this problem consists.

Hi, I have Arch Linux as my hosted OS. After I pull down the docker image and I can't execute `nvidia-smi` in the nvidia-docker container.
The error message is 
`zsh: exec format error: nvidia-smi`

**Comment by Kongsea** [comment]
My hosted OS is Ubuntu, and I have not met the error as you. @imyhxy
