### ISSUE TITLE
Is segmentation crucial for training?

### ISSUE THREAD

**Issue by mosheliv** [TuSimple/simpledet#150]
The readme states that the required fields are 
```[
    {
        "gt_class": (nBox, ),
        "gt_bbox": (nBox, 4),
        "flipped": bool,
        "h": int,
        "w": int,
        "image_url": str,
        "im_id": int,
        
        # this fields are generated on the fly during test
        "rec_id": int,
        "resize_h": int,
        "resize_w": int,
        ...
    },
    ...
]
```

However looking at the converter it seems to assume segmentation polygons are part of the data:
```
        roi_rec = {
            'image_url': 'data/%s/images/%s/%s' % (dataset_name, split, im_filename),
            'im_id': img_id,
            'h': im_h,
            'w': im_w,
            'gt_class': gt_class,
            'gt_bbox': gt_bbox,
            'gt_poly': gt_poly,
            'flipped': False}


```
Can I train a model without segmentation data? Are there some models that require it and some that do not?

**Comment by xchani** [comment]
Only instance segmentation model requires that, such as **Mask R-CNN**. For general detection model, it is not necessary.

**Comment by mosheliv** [comment]
Thanks. Is htc a segmentation model? Its a bit unclear to me

**Comment by mosheliv** [comment]
Sorry cascade

**Comment by xchani** [comment]
**Cascade R-CNN** is implemented for detection task rather than segmentation.

**Comment by mosheliv** [comment]
Thanks!
