### ISSUE TITLE
run make 时报错

### ISSUE THREAD

**Issue by 2110317008** [TuSimple/simpledet#152]
home/simpledet# make
cd operator_py/cython/; python3 setup.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 46, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by RogerChern** [comment]
It seems CUDA environment on your machine is not properly set up. Please try the docker solution.

**Comment by 2110317008** [comment]
> It seems CUDA environment on your machine is not properly set up. Please try the docker solution.

But I ran the program under my docker and it worked well.

**Comment by 2110317008** [comment]
In the program running in docker, the cuda path in docker is /usr/local/cuda. Is it necessary to change the 58 lines of set.py file CUDA = locate_cuda()?Thank you！

**Comment by RogerChern** [comment]
Check you `PATH` environment variable to see if `/usr/local/cuda/bin` in it.
