### ISSUE TITLE
new commits has bug for Trident

### ISSUE THREAD

**Issue by Tveek** [TuSimple/simpledet#157]
run this `python3 detection_train.py --config config/tridentnet_r50v2c4_c5_2x.py`
get below
`raceback (most recent call last):
  File "detection_train.py", line 278, in <module>
    train_net(parse_args())
  File "detection_train.py", line 21, in train_net
    transform, data_name, label_name, metric_list = config.get_config(is_train=True)
  File "/pathto/simpledet/config/tridentnet_r50v2c4_c5_2x.py", line 133, in get_config
    num_branch=Trident.num_branch, scaleaware=Trident.train_scaleaware)
  File "/pathto/simpledet/models/tridentnet/builder.py", line 84, in get_train_symbol
    rpn_loss = rpn_head.get_loss(rpn_feat, rpn_cls_label, rpn_reg_target, rpn_reg_weight)
TypeError: get_loss() takes 4 positional arguments but 5 were given`

in symbol/builder.py, RpnHead.get_loss(self, conv_feat, gt_bboxes, im_infos)

**Comment by RogerChern** [comment]
I believe this bug is already fixed yesterday with #156

**Comment by RogerChern** [comment]
Besides, consider giving a try of [tridentnet](https://github.com/TuSimple/simpledet/blob/master/config/resnet_v1b/tridentnet_r50v1bc4_c5_1x.py) with the new resnet_v1b backbones. They perform even better.

**Comment by Tveek** [comment]
@RogerChern thanks, but Bugs still exist.you can test again

**Comment by Tveek** [comment]
RpnHead.get_loss def like this:
`def get_loss(self, conv_feat, gt_bboxes, im_infos):`
but using :
`rpn_head.get_loss(rpn_feat, rpn_cls_label, rpn_reg_target, rpn_reg_weight)`

**Comment by RogerChern** [comment]
Hi @Tveek ,  sorry for the inconvenience. I've temporarily patched tridentnet. We will refactor the interface consistently later.
