### ISSUE TITLE
Hello, what the 1X or 2X means in train schedule?

### ISSUE THREAD

**Issue by z-huabao** [TuSimple/simpledet#167]
[model zoo](https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md)

another question: why not use TridentNet+R-FCN but Faster-RCNN?

**Comment by RogerChern** [comment]
1x means training 12 epochs, and 2x as 24 epochs.
R-FCN is a good work, but we do not have a solid baseline model on that. On the other hands, Faster R-CNN is more widely adopted.

**Comment by z-huabao** [comment]
ok, I see, thanks for your answer!

**Comment by wkcn** [comment]
Hi @RogerChern , I don't know why the epoch is 6 in [faster_r101v1_fpn_1x.py](https://github.com/TuSimple/simpledet/blob/master/config/faster_r101v1_fpn_1x.py#L165), and the epoch is 12 in [faster_r101v1_fpn_2x.py](https://github.com/TuSimple/simpledet/blob/master/config/faster_r101v1_fpn_2x.py#L165).

**Comment by RogerChern** [comment]
We pre-flip all the images. So 1 epoch in SimpleDet counts as 2.

**Comment by wkcn** [comment]
@RogerChern I see. Thank you!
