### ISSUE TITLE
AttributeError: module 'mxnet.symbol.contrib' has no attribute 'Proposal_v3'

### ISSUE THREAD

**Issue by 15122901359** [TuSimple/simpledet#171]

**Comment by louielu1027** [comment]
i meet the same error...

**Comment by RogerChern** [comment]
@louielu1027, this error indicates you did not set up simpledet correctly. You can try out the pre-built python wheel provided in [INSTALL.md](doc/INSTALL.md) and this problem should go away.

**Comment by rohun-tripathi** [comment]
The pre-built python wheel for cuda100 does not download the package - 

It hangs with the following output - 

--2019-10-07 01:10:51--  https://bit.ly/2jRGqdc
Resolving bit.ly... 67.199.248.10, 67.199.248.11
Connecting to bit.ly|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://simpledet.alarge.space:1234/?/mxnet_cu100-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl [following]
--2019-10-07 01:10:51--  http://simpledet.alarge.space:1234/?/mxnet_cu100-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl
Resolving simpledet.alarge.space... 39.97.110.197
Connecting to simpledet.alarge.space|39.97.110.197|:1234...

**Comment by rohun-tripathi** [comment]
This link works - https://1dv.alarge.space/mxnet_cu100-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl

**Comment by KelvinHuang666** [comment]
good job,thx

**Comment by alen-mask** [comment]
> This link works - https://1dv.alarge.space/mxnet_cu100-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl

I install this version of mxnet but the error still exists...
cuda 10.0, centos 7. python3.7

**Comment by alen-mask** [comment]
and i create the anaconda environment according to https://blog.csdn.net/surserrr/article/details/100654545,
this error log still exists...
cuda10.0   python3.6
