### ISSUE TITLE
Install MXNet  

### ISSUE THREAD

**Issue by molyswu** [TuSimple/simpledet#174]
Install MXNet for error:

git clone --recursive https://github.com/apache/incubator-mxnet /tmp/mxnet && \
git clone https://github.com/Tusimple/simpledet /tmp/simpledet && \
git clone https://github.com/RogerChern/cocoapi /tmp/cocoapi && \
cp -r /tmp/simpledet/operator_cxx/* /tmp/mxnet/src/operator && \
mkdir -p /tmp/mxnet/src/coco_api && \
cp -r /tmp/cocoapi/common /tmp/mxnet/src/coco_api && \
cd /tmp/mxnet && \
echo "USE_SIGNAL_HANDLER = 1" >> ./config.mk && \
echo "USE_OPENCV = 0" >> ./config.mk && \
echo "USE_MKLDNN = 0" >> ./config.mk && \
echo "USE_BLAS = openblas" >> ./config.mk && \
echo "USE_CUDA = 1" >> ./config.mk && \
echo "USE_CUDA_PATH = /usr/local/cuda" >> ./config.mk && \
echo "USE_CUDNN = 1" >> ./config.mk && \
echo "USE_NCCL = 1" >> ./config.mk && \
echo "USE_DIST_KVSTORE = 1" >> ./config.mk && \
echo "CUDA_ARCH = -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70" >> ./config.mk && \
make -j$((`nproc`-1)) && \
cd python && \
python3 setup.py install && \
rm -rf /tmp/mxnet /tmp/simpledet /tmp/cocoapi

-Wl,--whole-archive /tmp/mxnet/3rdparty/tvm/nnvm/lib/libnnvm.a -Wl,--no-whole-archive
a - build/src/operator/tensor/elemwise_binary_op_logic.o
a - build/src/operator/tensor/elemwise_binary_op_extended.o
a - build/src/operator/tensor/square_sum.o
a - build/src/operator/tensor/matrix_op.o
a - build/src/operator/tensor/elemwise_binary_op_basic.o
a - build/src/operator/tensor/init_op.o
a - build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o
a - build/src/operator/tensor/elemwise_sum.o
a - build/src/operator/tensor/histogram.o
a - build/src/operator/tensor/broadcast_reduce_op_index.o
a - build/src/operator/tensor/elemwise_scatter_op.o
a - build/src/operator/tensor/elemwise_unary_op_basic.o
a - build/src/operator/tensor/ravel.o
a - build/src/operator/tensor/broadcast_reduce_op_value.o
a - build/src/operator/tensor/elemwise_binary_op.o
a - build/src/operator/tensor/control_flow_op.o
a - build/src/operator/tensor/amp_cast.o
a - build/src/operator/tensor/indexing_op.o
a - build/src/operator/tensor/ordering_op.o
a - build/src/operator/tensor/dot.o
a - build/src/operator/tensor/cast_storage.o
a - build/src/operator/tensor/la_op.o
a - build/src/operator/tensor/elemwise_binary_broadcast_op_logic.o
a - build/src/operator/tensor/diag_op.o
a - build/src/operator/tensor/sparse_retain.o
a - build/src/operator/tensor/elemwise_binary_scalar_op_extended.o
a - build/src/operator/tensor/elemwise_binary_scalar_op_basic.o
a - build/src/operator/tensor/elemwise_binary_scalar_op_logic.o
a - build/src/operator/tensor/elemwise_unary_op_trig.o
a - build/src/operator/tvmop/op_module.o
a - build/src/operator/nnpack/nnpack_util.o
a - build/src/operator/contrib/count_sketch.o
a - build/src/operator/contrib/nnz.o
a - build/src/operator/contrib/proposal_v3.o
a - build/src/operator/contrib/optimizer_op.o
a - build/src/operator/contrib/fft.o
a - build/src/operator/contrib/multibox_prior.o
a - build/src/operator/contrib/hawkes_ll.o
a - build/src/operator/contrib/transformer.o
a - build/src/operator/contrib/all_finite.o
a - build/src/operator/contrib/krprod.o
a - build/src/operator/contrib/index_copy.o
a - build/src/operator/contrib/sync_inplace_activation_batch_norm.o
a - build/src/operator/contrib/amp_graph_pass.o
a - build/src/operator/contrib/psroi_pooling.o
a - build/src/operator/contrib/sigmoid_cross_entropy.o
a - build/src/operator/contrib/multibox_detection.o
a - build/src/operator/contrib/adaptive_avg_pooling.o
a - build/src/operator/contrib/generate_proposal.o
a - build/src/operator/contrib/generate_anchor.o
a - build/src/operator/contrib/multibox_target.o
a - build/src/operator/contrib/proposal.o
a - build/src/operator/contrib/quadratic_op.o
a - build/src/operator/contrib/generate_proposal_retina.o
a - build/src/operator/contrib/axpy.o
a - build/src/operator/contrib/deformable_convolution.o
a - build/src/operator/contrib/broadcast_scale.o
a - build/src/operator/contrib/nms.o
a - build/src/operator/contrib/deformable_psroi_pooling.o
a - build/src/operator/contrib/dgl_graph.o
a - build/src/operator/contrib/gradient_multiplier_op.o
a - build/src/operator/contrib/adamw.o
a - build/src/operator/contrib/focal_loss.o
a - build/src/operator/contrib/multi_proposal.o
a - build/src/operator/contrib/roi_align.o
a - build/src/operator/contrib/bounding_box.o
a - build/src/operator/contrib/group_norm.o
a - build/src/operator/contrib/decodebbox.o
a - build/src/operator/contrib/bilinear_resize.o
a - build/src/operator/contrib/index_array.o
a - build/src/operator/contrib/boolean_mask.o
a - build/src/operator/contrib/proposal_v2.o
a - build/src/operator/contrib/bbox_norm.o
a - build/src/operator/contrib/ifft.o
a - build/src/operator/contrib/global_average_pooling.o
a - build/src/operator/contrib/roi_align_v2.o
a - build/src/operator/contrib/sync_batch_norm.o
a - build/src/operator/custom/native_op.o
a - build/src/operator/custom/ndarray_op.o
a - build/src/operator/custom/custom.o
a - build/src/operator/image/crop.o
a - build/src/operator/image/image_random.o
a - build/src/operator/image/resize.o
a - build/src/coco_api/common/maskApi.o
a - build/src/io/io.o
a - build/src/io/image_aug_default.o
a - build/src/io/iter_image_det_recordio.o
a - build/src/io/image_io.o
a - build/src/io/image_det_aug_default.o
a - build/src/io/iter_csv.o
a - build/src/io/iter_image_recordio.o
a - build/src/io/iter_mnist.o
a - build/src/io/iter_image_recordio_2.o
a - build/src/io/iter_libsvm.o
a - build/src/common/utils.o
a - build/src/common/rtc.o
a - build/src/nnvm/gradient.o
a - build/src/nnvm/legacy_op_util.o
a - build/src/nnvm/tvm_bridge.o
a - build/src/nnvm/graph_editor.o
a - build/src/nnvm/legacy_json_util.o
a - build/src/nnvm/plan_memory.o
a - build/src/nnvm/low_precision_pass.o
a - build/src/nnvm/amp_infer_unknown.o
a - build/src/profiler/profiler.o
a - build/src/profiler/aggregate_stats.o
a - build/src/profiler/nvtx.o
a - build/src/profiler/vtune.o
a - build/src/imperative/cached_op.o
a - build/src/imperative/imperative_utils.o
a - build/src/imperative/imperative.o
a - build/src/ndarray/ndarray_function.o
a - build/src/ndarray/ndarray.o
a - build/src/operator/instance_norm.o
a - build/src/operator/svm_output.o
a - build/src/operator/loss_binary_op.o
a - build/src/operator/rnn.o
a - build/src/operator/convolution_v1.o
a - build/src/operator/proposal_mask_target.o
a - build/src/operator/sequence_reverse.o
a - build/src/operator/pad.o
a - build/src/operator/softmax_output.o
a - build/src/operator/leaky_relu.o
a - build/src/operator/operator_util.o
a - build/src/operator/crop.o
a - build/src/operator/batch_norm_v1.o
a - build/src/operator/swapaxis.o
a - build/src/operator/sequence_last.o
a - build/src/operator/operator.o
a - build/src/operator/optimizer_op.o
a - build/src/operator/proposal_target_v2.o
a - build/src/operator/grid_generator.o
a - build/src/operator/correlation.o
a - build/src/operator/roi_pooling_v1.o
a - build/src/operator/sequence_mask.o
a - build/src/operator/spatial_transformer.o
a - build/src/operator/pooling_v1.o
a - build/src/operator/subgraph_op_common.o
a - build/src/operator/identity_attach_KL_sparse_reg.o
a - build/src/operator/bilinear_sampler.o
a - build/src/operator/roi_pooling.o
a - build/src/operator/cross_device_copy.o
a - build/src/operator/regression_output.o
a - build/src/operator/make_loss.o
a - build/src/operator/c_lapack_api.o
a - build/src/operator/operator_tune.o
a - build/src/operator/slice_channel.o
a - build/src/operator/l2_normalization.o
a - build/src/operator/control_flow.o
a - build/src/operator/proposal_target.o
a - build/src/engine/naive_engine.o
a - build/src/engine/openmp.o
a - build/src/engine/threaded_engine_pooled.o
a - build/src/engine/engine.o
a - build/src/engine/threaded_engine.o
a - build/src/engine/threaded_engine_perdevice.o
a - build/src/storage/storage.o
a - build/src/c_api/c_api_symbolic.o
a - build/src/c_api/c_api_profile.o
a - build/src/c_api/c_api_ndarray.o
a - build/src/c_api/c_api_test.o
a - build/src/c_api/c_api_executor.o
a - build/src/c_api/c_predict_api.o
a - build/src/c_api/c_api_function.o
a - build/src/c_api/c_api.o
a - build/src/c_api/c_api_error.o
a - build/src/executor/inplace_addto_detect_pass.o
a - build/src/executor/infer_graph_attr_pass.o
a - build/src/executor/graph_executor.o
a - build/src/executor/attach_op_execs_pass.o
a - build/src/executor/attach_op_resource_pass.o
a - build/src/kvstore/gradient_compression.o
a - build/src/kvstore/kvstore_utils.o
a - build/src/kvstore/kvstore.o
a - build/src/resource.o
a - build/src/base.o
a - build/src/libinfo.o
a - build/src/initialize.o
a - build/src/operator/subgraph/tensorrt/tensorrt_gpu.o
a - build/src/operator/nn/cudnn/cudnn_batch_norm_gpu.o
a - build/src/operator/nn/dropout_gpu.o
a - build/src/operator/nn/fully_connected_gpu.o
a - build/src/operator/nn/softmax_activation_gpu.o
a - build/src/operator/nn/concat_gpu.o
a - build/src/operator/nn/lrn_gpu.o
a - build/src/operator/nn/group_norm_gpu.o
a - build/src/operator/nn/deconvolution_gpu.o
a - build/src/operator/nn/pooling_gpu.o
a - build/src/operator/nn/softmax_gpu.o
a - build/src/operator/nn/moments_gpu.o
a - build/src/operator/nn/activation_gpu.o
a - build/src/operator/nn/ctc_loss_gpu.o
a - build/src/operator/nn/upsampling_gpu.o
a - build/src/operator/nn/batch_norm_gpu.o
a - build/src/operator/nn/layer_norm_gpu.o
a - build/src/operator/nn/convolution_gpu.o
a - build/src/operator/quantization/requantize_gpu.o
a - build/src/operator/quantization/quantize_gpu.o
a - build/src/operator/quantization/dequantize_gpu.o
a - build/src/operator/quantization/quantized_conv_gpu.o
a - build/src/operator/quantization/quantized_flatten_gpu.o
a - build/src/operator/quantization/quantized_fully_connected_gpu.o
a - build/src/operator/quantization/quantized_pooling_gpu.o
a - build/src/operator/quantization/quantize_v2_gpu.o
a - build/src/operator/random/shuffle_op_gpu.o
a - build/src/operator/random/pdf_op_gpu.o
a - build/src/operator/random/sample_multinomial_op_gpu.o
a - build/src/operator/random/multisample_op_gpu.o
a - build/src/operator/random/sample_op_gpu.o
a - build/src/operator/tensor/elemwise_binary_op_basic_gpu.o
a - build/src/operator/tensor/elemwise_binary_scalar_op_basic_gpu.o
a - build/src/operator/tensor/elemwise_binary_scalar_op_extended_gpu.o
a - build/src/operator/tensor/ordering_op_gpu.o
a - build/src/operator/tensor/cast_storage_gpu.o
a - build/src/operator/tensor/elemwise_binary_broadcast_op_logic_gpu.o
a - build/src/operator/tensor/matrix_op_gpu.o
a - build/src/operator/tensor/elemwise_unary_op_trig_gpu.o
a - build/src/operator/tensor/broadcast_reduce_op_index_gpu.o
a - build/src/operator/tensor/elemwise_binary_broadcast_op_basic_gpu.o
a - build/src/operator/tensor/square_sum_gpu.o
a - build/src/operator/tensor/elemwise_binary_op_extended_gpu.o
a - build/src/operator/tensor/elemwise_sum_gpu.o
a - build/src/operator/tensor/init_op_gpu.o
a - build/src/operator/tensor/elemwise_binary_scalar_op_logic_gpu.o
a - build/src/operator/tensor/dot_gpu.o
a - build/src/operator/tensor/amp_cast_gpu.o
a - build/src/operator/tensor/control_flow_op_gpu.o
a - build/src/operator/tensor/ravel_gpu.o
a - build/src/operator/tensor/broadcast_reduce_op_value_gpu.o
a - build/src/operator/tensor/elemwise_binary_broadcast_op_extended_gpu.o
a - build/src/operator/tensor/histogram_gpu.o
a - build/src/operator/tensor/elemwise_scatter_op_gpu.o
a - build/src/operator/tensor/indexing_op_gpu.o
a - build/src/operator/tensor/la_op_gpu.o
a - build/src/operator/tensor/sparse_retain_gpu.o
a - build/src/operator/tensor/diag_op_gpu.o
a - build/src/operator/tensor/elemwise_unary_op_basic_gpu.o
a - build/src/operator/tensor/elemwise_binary_op_logic_gpu.o
a - build/src/operator/contrib/ifft_gpu.o
a - build/src/operator/contrib/optimizer_op_gpu.o
a - build/src/operator/contrib/group_norm_helper_gpu.o
a - build/src/operator/contrib/psroi_pooling_gpu.o
a - build/src/operator/contrib/deformable_convolution_gpu.o
a - build/src/operator/contrib/multibox_detection_gpu.o
a - build/src/operator/contrib/adaptive_avg_pooling_gpu.o
a - build/src/operator/contrib/generate_proposal_gpu.o
a - build/src/operator/contrib/generate_anchor_gpu.o
a - build/src/operator/contrib/multibox_target_gpu.o
a - build/src/operator/contrib/index_array_gpu.o
a - build/src/operator/contrib/sigmoid_cross_entropy_gpu.o
a - build/src/operator/contrib/gradient_multiplier_op_gpu.o
a - build/src/operator/contrib/global_average_pooling_gpu.o
a - build/src/operator/contrib/axpy_gpu.o
a - build/src/operator/contrib/generate_proposal_retina_gpu.o
a - build/src/operator/contrib/proposal_gpu.o
a - build/src/operator/contrib/broadcast_scale_gpu.o
a - build/src/operator/contrib/nms_gpu.o
a - build/src/operator/contrib/deformable_psroi_pooling_gpu.o
a - build/src/operator/contrib/adamw_gpu.o
a - build/src/operator/contrib/quadratic_op_gpu.o
a - build/src/operator/contrib/focal_loss_gpu.o
a - build/src/operator/contrib/multi_proposal_gpu.o
a - build/src/operator/contrib/bbox_norm_gpu.o
a - build/src/operator/contrib/roi_align_gpu.o
a - build/src/operator/contrib/bilinear_resize_gpu.o
a - build/src/operator/contrib/boolean_mask_gpu.o
a - build/src/operator/contrib/proposal_v2_gpu.o
a - build/src/operator/contrib/sync_batch_norm_gpu.o
a - build/src/operator/contrib/index_copy_gpu.o
a - build/src/operator/contrib/count_sketch_gpu.o
a - build/src/operator/contrib/fft_gpu.o
a - build/src/operator/contrib/all_finite_gpu.o
a - build/src/operator/contrib/proposal_v3_gpu.o
a - build/src/operator/contrib/sync_inplace_activation_batch_norm_gpu.o
a - build/src/operator/contrib/bounding_box_gpu.o
a - build/src/operator/contrib/dgl_graph_gpu.o
a - build/src/operator/contrib/group_norm_gpu.o
a - build/src/operator/contrib/multibox_prior_gpu.o
a - build/src/operator/contrib/hawkes_ll_gpu.o
a - build/src/operator/contrib/roi_align_v2_gpu.o
a - build/src/operator/contrib/transformer_gpu.o
a - build/src/operator/custom/native_op_gpu.o
a - build/src/operator/image/resize_gpu.o
a - build/src/operator/image/image_random_gpu.o
a - build/src/common/utils_gpu.o
a - build/src/common/random_generator_gpu.o
a - build/src/ndarray/ndarray_function_gpu.o
a - build/src/operator/svm_output_gpu.o
a - build/src/operator/optimizer_op_gpu.o
a - build/src/operator/pooling_v1_gpu.o
a - build/src/operator/sequence_mask_gpu.o
a - build/src/operator/leaky_relu_gpu.o
a - build/src/operator/identity_attach_KL_sparse_reg_gpu.o
a - build/src/operator/make_loss_gpu.o
a - build/src/operator/roi_pooling_gpu.o
a - build/src/operator/loss_binary_op_gpu.o
a - build/src/operator/regression_output_gpu.o
a - build/src/operator/l2_normalization_gpu.o
a - build/src/operator/slice_channel_gpu.o
a - build/src/operator/bilinear_sampler_gpu.o
a - build/src/operator/pad_gpu.o
a - build/src/operator/correlation_gpu.o
a - build/src/operator/instance_norm_gpu.o
a - build/src/operator/roi_pooling_v1_gpu.o
a - build/src/operator/grid_generator_gpu.o
a - build/src/operator/rnn_gpu.o
a - build/src/operator/convolution_v1_gpu.o
a - build/src/operator/crop_gpu.o
a - build/src/operator/sequence_reverse_gpu.o
a - build/src/operator/spatial_transformer_gpu.o
a - build/src/operator/swapaxis_gpu.o
a - build/src/operator/softmax_output_gpu.o
a - build/src/operator/batch_norm_v1_gpu.o
a - build/src/operator/sequence_last_gpu.o
a - build/src/kvstore/gradient_compression_gpu.o
a - build/src/kvstore/kvstore_utils_gpu.o
build/src/operator/contrib/group_norm.o: In function `mxnet::op::GroupNormParam::__MANAGER__()':
group_norm.cc:(.text+0x380): multiple definition of `mxnet::op::GroupNormParam::__MANAGER__()'
build/src/operator/nn/group_norm.o:group_norm.cc:(.text+0x4910): first defined here
collect2: error: ld returned 1 exit status
Makefile:579: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1

Thanks!

**Comment by RogerChern** [comment]
Refer to #170
