### ISSUE TITLE
On setup with Docker  INSTALL  error

### ISSUE THREAD

**Issue by molyswu** [TuSimple/simpledet#177]
Setup with Docker  INSTALL :
git clone --recursive https://github.com/apache/incubator-mxnet /tmp/mxnet && \
git clone https://github.com/Tusimple/simpledet /tmp/simpledet && \
git clone https://github.com/RogerChern/cocoapi /tmp/cocoapi && \
cp -r /tmp/simpledet/operator_cxx/* /tmp/mxnet/src/operator && \
mkdir -p /tmp/mxnet/src/coco_api && \
cp -r /tmp/cocoapi/common /tmp/mxnet/src/coco_api && \
cd /tmp/mxnet && \
echo "USE_SIGNAL_HANDLER = 1" >> ./config.mk && \
echo "USE_OPENCV = 0" >> ./config.mk && \
echo "USE_MKLDNN = 0" >> ./config.mk && \
echo "USE_BLAS = openblas" >> ./config.mk && \
echo "USE_CUDA = 1" >> ./config.mk && \
echo "USE_CUDA_PATH = /usr/local/cuda" >> ./config.mk && \
echo "USE_CUDNN = 1" >> ./config.mk && \
echo "USE_NCCL = 1" >> ./config.mk && \
echo "USE_DIST_KVSTORE = 1" >> ./config.mk && \
echo "CUDA_ARCH = -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70" >> ./config.mk && \
rm /tmp/mxnet/src/operator/nn/group_norm* && \
make -j$((`nproc`-1)) && \

root@456ccd747048 /mxnet# cd python                                 2 75a9e18!?
root@456ccd747048 /m/python# python3 setup.py install                 75a9e18!?
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 74, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the MXNet library.
List of candidates:
/usr/local/nvidia/lib/libmxnet.so
/usr/local/nvidia/lib64/libmxnet.so
/usr/local/lib/libmxnet.so
/usr/local/nvidia/lib/libmxnet.so
/usr/local/nvidia/lib64/libmxnet.so
/usr/local/cuda/lib64/stubs/libmxnet.so
/mxnet/python/mxnet/libmxnet.so
/mxnet/python/mxnet/../../lib/libmxnet.so
/mxnet/python/mxnet/../../build/libmxnet.so
../../../libmxnet.so

Thanks!

**Comment by RogerChern** [comment]
The docker image has already included a pre-built MXNet for simpledet.
