### ISSUE TITLE
run nasfpn_1280 timeout

### ISSUE THREAD

**Issue by 15122901359** [TuSimple/simpledet#179]
hello , it always stay "Running performance tests to find the best convolution algorithm, this can take a while...". when i  run retina_r50v1b_nasfpn_1280_7@384_25epoch.py with 2X 2080Ti .

**Comment by RogerChern** [comment]
This is generally because you are using a wrong CUDA/cuDNN lib. Please try to pull the CUDA10 docker to see if this problem persists.

**Comment by 15122901359** [comment]
@RogerChern thanks, I will try to pull the CUDA10 docker.
