### ISSUE TITLE
Traning stop error in Nvidia-socker

### ISSUE THREAD

**Issue by dl19940602** [TuSimple/simpledet#182]
Hi,when i training my own datasets on tridentnet_r50v2c4_c5_1x.py, it stop training in Epoch[0] and dosen't training any more, without any params saved; i try several times but failed, how can i solve this problem? Thank you!
#19

**Comment by xchani** [comment]
Please attach your training log for analysis.

**Comment by RogerChern** [comment]
I noticed that you are experimenting with your own dataset, so did the hang happen near the end of an epoch?

**Comment by dl19940602** [comment]
My batch size is 16 of 8GPUs, the training set has 4 classes, and training samples is 430000，it stop training at iter 59900。

**Comment by dl19940602** [comment]
> Please attach your training log for analysis.

![trident](https://user-images.githubusercontent.com/31540517/62421561-2f0abc00-b6d6-11e9-94fa-69a8094ddafa.png)

**Comment by dl19940602** [comment]
@RogerChern yes it happen near the end of an epoch! so how could i do now?

**Comment by RogerChern** [comment]
@dl19940602 
Mostly this is related to data loader not being reset correctly. Could you please kindly share your config with us for further debug?

**Comment by dl19940602** [comment]
@RogerChern  cp_coco is my own datasets
from models.tridentnet.builder import TridentFasterRcnn as Detector
from models.tridentnet.builder import TridentResNetV1bC4 as Backbone
from models.tridentnet.builder import TridentRpnHead as RpnHead
from models.tridentnet.builder import process_branch_outputs, process_branch_rpn_outputs
from symbol.builder import Neck
from symbol.builder import RoiAlign as RoiExtractor
from symbol.builder import BboxC5V1Head as BboxHead
from mxnext.complicate import normalizer_factory


def get_config(is_train):
    class General:
        log_frequency = 10
        name = __name__.rsplit("/")[-1].rsplit(".")[-1]
        batch_image = 2 if is_train else 1
        fp16 = False

    class Trident:
        num_branch = 3
        train_scaleaware = True
        test_scaleaware = True
        branch_ids = range(num_branch)
        branch_dilates = [1, 2, 3]
        valid_ranges = [(0, 90), (30, 160), (90, -1)]
        valid_ranges_on_origin = True
        branch_bn_shared = True
        branch_conv_shared = True
        branch_deform = False

        assert num_branch == len(branch_ids)
        assert num_branch == len(valid_ranges)

    class KvstoreParam:
        kvstore     = "local"
        batch_image = General.batch_image
        gpus        = [0, 1, 2, 3, 4, 5, 6]
        fp16        = General.fp16

    class NormalizeParam:
        # normalizer = normalizer_factory(type="syncbn", ndev=len(KvstoreParam.gpus))
        normalizer = normalizer_factory(type="fixbn")

    class BackboneParam:
        fp16 = General.fp16
        normalizer = NormalizeParam.normalizer
        depth = 50
        num_branch = Trident.num_branch
        branch_ids = Trident.branch_ids
        branch_dilates = Trident.branch_dilates
        branch_bn_shared = Trident.branch_bn_shared
        branch_conv_shared = Trident.branch_conv_shared
        branch_deform = Trident.branch_deform

    class NeckParam:
        fp16 = General.fp16
        normalizer = NormalizeParam.normalizer


    class RpnParam:
        fp16 = General.fp16
        normalizer = NormalizeParam.normalizer
        batch_image = General.batch_image * Trident.num_branch

        class anchor_generate:
            scale = (2, 4, 8, 16, 32)
            ratio = (0.5, 1.0, 2.0)
            stride = 16
            image_anchor = 256

        class head:
            conv_channel = 512
            mean = (0, 0, 0, 0)
            std = (1, 1, 1, 1)

        class proposal:
            pre_nms_top_n = 12000 if is_train else 6000
            post_nms_top_n = 500 if is_train else 300
            nms_thr = 0.7
            min_bbox_side = 0

        class subsample_proposal:
            proposal_wo_gt = True
            image_roi = 128
            fg_fraction = 0.5
            fg_thr = 0.5
            bg_thr_hi = 0.5
            bg_thr_lo = 0.0

        class bbox_target:
            num_reg_class = 2
            class_agnostic = True
            weight = (1.0, 1.0, 1.0, 1.0)
            mean = (0.0, 0.0, 0.0, 0.0)
            std = (0.1, 0.1, 0.2, 0.2)


    class BboxParam:
        fp16        = General.fp16
        normalizer  = NormalizeParam.normalizer
        num_class   = 1 + 4
        image_roi   = 128
        batch_image = General.batch_image * Trident.num_branch

        class regress_target:
            class_agnostic = True
            mean = (0.0, 0.0, 0.0, 0.0)
            std = (0.1, 0.1, 0.2, 0.2)


    class RoiParam:
        fp16 = General.fp16
        normalizer = NormalizeParam.normalizer
        out_size = 7
        stride = 16


    class DatasetParam:
        if is_train:
            image_set = ("cp_coco_train",)
        else:
            image_set = ("cp_coco_val", )

    backbone = Backbone(BackboneParam)
    neck = Neck(NeckParam)
    rpn_head = RpnHead(RpnParam)
    roi_extractor = RoiExtractor(RoiParam)
    bbox_head = BboxHead(BboxParam)
    detector = Detector()
    if is_train:
        train_sym = detector.get_train_symbol(
            backbone, neck, rpn_head, roi_extractor, bbox_head,
            num_branch=Trident.num_branch, scaleaware=Trident.train_scaleaware)
        rpn_test_sym = None
        test_sym = None
    else:
        train_sym = None
        rpn_test_sym = detector.get_rpn_test_symbol(backbone, neck, rpn_head, Trident.num_branch)
        test_sym = detector.get_test_symbol(
            backbone, neck, rpn_head, roi_extractor, bbox_head, num_branch=Trident.num_branch)


    class ModelParam:
        train_symbol = train_sym
        test_symbol = test_sym
        rpn_test_symbol = rpn_test_sym

        from_scratch = False
        random = True
        memonger = False
        memonger_until = "stage3_unit21_plus"

        class pretrain:
            prefix = "pretrain_model/resnet%s_v1b" % BackboneParam.depth
            epoch = 0
            fixed_param = ["conv0", "stage1", "gamma", "beta"]


    class OptimizeParam:
        class optimizer:
            type = "sgd"
            lr = 0.01 / 8 * len(KvstoreParam.gpus) * KvstoreParam.batch_image
            momentum = 0.9
            wd = 0.0001
            clip_gradient = 5

        class schedule:
            begin_epoch = 0
            end_epoch = 6
            lr_iter = [60000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image),
                       80000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)]

        class warmup:
            type = "gradual"
            lr = 0.0
            iter = 3000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)


    class TestParam:
        min_det_score = 0.001
        max_det_per_image = 100

        process_roidb = lambda x: x
        if Trident.test_scaleaware:
            process_output = lambda x, y: process_branch_outputs(
                x, Trident.num_branch, Trident.valid_ranges, Trident.valid_ranges_on_origin)
        else:
            process_output = lambda x, y: x

        process_rpn_output = lambda x, y: process_branch_rpn_outputs(x, Trident.num_branch)

        class model:
            prefix = "experiments/{}/checkpoint".format(General.name)
            epoch = OptimizeParam.schedule.end_epoch

        class nms:
            type = "nms"
            thr = 0.5

        class coco:
            annotation = "data/cp_coco/annotations/instances_val.json"

    # data processing
    class NormParam:
        mean = tuple(i * 255 for i in (0.485, 0.456, 0.406)) # RGB order
        std = tuple(i * 255 for i in (0.229, 0.224, 0.225))

    class ResizeParam:
        short = 800
        long = 1200 if is_train else 2000


    class PadParam:
        short = 800
        long = 1200 if is_train else 2000
        max_num_gt = 100

    class ScaleRange:
        valid_ranges = Trident.valid_ranges
        cal_on_origin = Trident.valid_ranges_on_origin # True: valid_ranges on origin image scale / valid_ranges on resized image scale

    class AnchorTarget2DParam:
        class generate:
            short = 800 // 16
            long = 1200 // 16
            stride = 16
            scales = (2, 4, 8, 16, 32)
            aspects = (0.5, 1.0, 2.0)

        class assign:
            allowed_border = 0
            pos_thr = 0.7
            neg_thr = 0.3
            min_pos_thr = 0.0

        class sample:
            image_anchor = 256
            pos_fraction = 0.5

        class trident:
            invalid_anchor_threshd = 0.3


    class RenameParam:
        mapping = dict(image="data")


    from core.detection_input import ReadRoiRecord, Resize2DImageBbox, \
        ConvertImageFromHwcToChw, Flip2DImageBbox, Pad2DImageBbox, \
        RenameRecord, Norm2DImage
    from models.tridentnet.input import ScaleAwareRange, TridentAnchorTarget2D

    if is_train:
        transform = [
            ReadRoiRecord(None),
            Norm2DImage(NormParam),
            Resize2DImageBbox(ResizeParam),
            Flip2DImageBbox(),
            Pad2DImageBbox(PadParam),
            ConvertImageFromHwcToChw(),
            ScaleAwareRange(ScaleRange),
            TridentAnchorTarget2D(AnchorTarget2DParam),
            RenameRecord(RenameParam.mapping)
        ]
        data_name = ["data", "im_info", "gt_bbox"]
        if Trident.train_scaleaware:
            data_name.append("valid_ranges")
        label_name = ["rpn_cls_label", "rpn_reg_target", "rpn_reg_weight"]
    else:
        transform = [
            ReadRoiRecord(None),
            Norm2DImage(NormParam),
            Resize2DImageBbox(ResizeParam),
            ConvertImageFromHwcToChw(),
            RenameRecord(RenameParam.mapping)
        ]
        data_name = ["data", "im_info", "im_id", "rec_id"]
        label_name = []

    import core.detection_metric as metric

    rpn_acc_metric = metric.AccWithIgnore(
        "RpnAcc",
        ["rpn_cls_loss_output"],
        ["rpn_cls_label"]
    )
    rpn_l1_metric = metric.L1(
        "RpnL1",
        ["rpn_reg_loss_output"],
        ["rpn_cls_label"]
    )
    # for bbox, the label is generated in network so it is an output
    box_acc_metric = metric.AccWithIgnore(
        "RcnnAcc",
        ["bbox_cls_loss_output", "bbox_label_blockgrad_output"],
        []
    )
    box_l1_metric = metric.L1(
        "RcnnL1",
        ["bbox_reg_loss_output", "bbox_label_blockgrad_output"],
        []
    )

    metric_list = [rpn_acc_metric, rpn_l1_metric, box_acc_metric, box_l1_metric]

    return General, KvstoreParam, RpnParam, RoiParam, BboxParam, DatasetParam, \
           ModelParam, OptimizeParam, TestParam, \
           transform, data_name, label_name, metric_list

**Comment by RogerChern** [comment]
The config looks good to me except you are using 7 cards which should be fine. And are you doing single machine training or distributed training?
Could you please kindly report the value of `v_valid_count ` and `h_valid_count` by printing it in the `AnchorLoader` just below L817.  
https://github.com/TuSimple/simpledet/blob/5981d07a31827e41a68ca92985416a72a944434f/core/detection_input.py#L802-L817

**Comment by dl19940602** [comment]
@RogerChern Hi,i I adopt the distributed training; and i print it during the train,following are the numbers.
v_valid_count    0
h_valid_count   838682

**Comment by RogerChern** [comment]
@dl19940602 ,
Sorry, I fail to reproduce the bug by constructing the same the setting as yours. Could you please save the stdin & stdout to a text file for further debug?

**Comment by RogerChern** [comment]
Also, are you experiencing the same hang on the original coco dataset or other smaller datasets.

**Comment by dl19940602** [comment]
@RogerChern I did not meet the same hang on the original coco dataset, I only modify the num_class to 1+4 and image_set to my own datasets;I did not modify any other code。

**Comment by RogerChern** [comment]
@dl19940602 
Could you please try to limit your input to 1000 records by `roidb=roidb[:1000]` to see if this hang still persists?
https://github.com/TuSimple/simpledet/blob/5981d07a31827e41a68ca92985416a72a944434f/detection_train.py#L81-L83
I tried to manually create a roidb with horizontal 838682 entries but failed to reproduce the hang.

**Comment by dl19940602** [comment]
@RogerChern When I limit  input to 1000 records by roidb=roidb[:1000],it iter 70 every epoch and finish training in epoch 6, My training set is 437990, should i count roidb according to 437990/14=31285 ?
-0005.params"
08-06 13:25:07 Epoch[5] Batch [10]      Speed: 16.11 samples/sec        Train-RpnAcc=0.959238, RpnL1=0.287734, RcnnAcc=0.876699,       RcnnL1=1.434854,
08-06 13:25:16 Epoch[5] Batch [20]      Speed: 16.01 samples/sec        Train-RpnAcc=0.958665, RpnL1=0.289695, RcnnAcc=0.876442,       RcnnL1=1.429825,
08-06 13:25:24 Epoch[5] Batch [30]      Speed: 15.74 samples/sec        Train-RpnAcc=0.960541, RpnL1=0.286486, RcnnAcc=0.872385,       RcnnL1=1.443765,
08-06 13:25:33 Epoch[5] Batch [40]      Speed: 15.91 samples/sec        Train-RpnAcc=0.961632, RpnL1=0.294369, RcnnAcc=0.872118,       RcnnL1=1.432098,
08-06 13:25:42 Epoch[5] Batch [50]      Speed: 15.94 samples/sec        Train-RpnAcc=0.961479, RpnL1=0.299136, RcnnAcc=0.873375,       RcnnL1=1.431758,
08-06 13:25:51 Epoch[5] Batch [60]      Speed: 16.14 samples/sec        Train-RpnAcc=0.961775, RpnL1=0.299805, RcnnAcc=0.874982,       RcnnL1=1.429895,
08-06 13:26:00 Epoch[5] Batch [70]      Speed: 15.72 samples/sec        Train-RpnAcc=0.962030, RpnL1=0.297354, RcnnAcc=0.875448,       RcnnL1=1.425263,
08-06 13:26:00 Epoch[5] Train-RpnAcc=0.962030
08-06 13:26:00 Epoch[5] Train-RpnL1=0.297354
08-06 13:26:00 Epoch[5] Train-RcnnAcc=0.875448
08-06 13:26:00 Epoch[5] Train-RcnnL1=1.425263
08-06 13:26:00 Epoch[5] Time cost=64.160
08-06 13:26:01 Saved checkpoint to "experiments/faster_r50v1bc4_c5_512roi_1x/checkpoint-0006.params"
08-06 13:26:01 Training has done
08-06 13:26:11 Exiting

**Comment by RogerChern** [comment]
Should be 437990 * 2 / 14 = 62570 since we count the original input + flipped input as one epoch. So the hang happens near epoch 0 iteration 62570?

**Comment by dl19940602** [comment]
@RogerChern  the hang happens near epoch 0 iteration 59900, not 62570。

**Comment by RogerChern** [comment]
59900 makes sense to me, as your h_roidb_count is 838682, and 838682 / 14 = 59905.  You do not hang on 1000 input, yet both 838682 and 1000 do not divide 14 evenly. I will try to run the same sized roidb on another machine. In the meanwhile, could you please try to reproduce this hang on a smaller roidb?

**Comment by dl19940602** [comment]
@RogerChern I limit input to 234532 records by roidb=roidb[:234532]; 234532 is the roidb of coco; i will try whether 234532 reproduce the hang.

**Comment by dl19940602** [comment]
@RogerChern Hi, i modify roidb=roidb[:234532], it did not reproduce the hang and train the whole epoch, May the problem lies in 838682 which is too bigger roidb?

**Comment by RogerChern** [comment]
I can not recall there is any kind of restriction on the size of roidb.
Maybe you can try to run with the whole dataset once more to see if it
still persists?

**Comment by dl19940602** [comment]
@RogerChern I tried and also i changed another network, it still hang at iter 59900, Now i want to use the shole datasets without flip, the roidb is 419341

    roidb = reduce(lambda x, y: x + y, roidbs)
    # filter empty image
    roidb = [rec for rec in roidb if rec["gt_bbox"].shape[0] > 0]
    # add flip roi record
    flipped_roidb = []
    for rec in roidb:
        new_rec = rec.copy()
        new_rec["flipped"] = True
        flipped_roidb.append(new_rec)
#    roidb = roidb + flipped_roidb
    print(len(roidb))
    from core.detection_input import AnchorLoader
    train_data = AnchorLoader(
        roidb=roidb,
        transform=transform,

**Comment by RogerChern** [comment]
@dl19940602 ,
I try to reproduce the hang in another machine but still fail. Here are my steps.

I manually copy the the first entry in roidb 838682 times to ensure there is only one aspect
```python
for rec in roidb:
    new_rec = rec.copy()
    new_rec["flipped"] = True
    flipped_roidb.append(new_rec)
roidb = roidb + flipped_roidb
roidb = [roidb[0]] * 838682
```

And then I run the training as usual with 7GPUs and 2 image/GPU, and I get

```
08-07 00:42:21 Epoch[0] Batch [59870]   Speed: 89.89 samples/sec        Train-RpnAcc=0.944921,  RpnL1=1833481622.527155,
08-07 00:42:22 Epoch[0] Batch [59880]   Speed: 89.68 samples/sec        Train-RpnAcc=0.944910,  RpnL1=1833175434.984807,
08-07 00:42:24 Epoch[0] Batch [59890]   Speed: 91.63 samples/sec        Train-RpnAcc=0.944899,  RpnL1=1832869349.690724,
08-07 00:42:25 Epoch[0] Batch [59900]   Speed: 91.85 samples/sec        Train-RpnAcc=0.944888,  RpnL1=1832563366.593699,
08-07 00:42:26 Epoch[0] Train-RpnAcc=0.944884
08-07 00:42:26 Epoch[0] Train-RpnL1=1832441001.958600
08-07 00:42:26 Epoch[0] Time cost=9351.246
08-07 00:42:26 Saved checkpoint to "experiments/debug/checkpoint-0001.params"
```

ignore the large loss due to numerical issue and the training does not hang.

Now I wonder what is the exact commit id of your simpledet.

**Comment by dl19940602** [comment]
@RogerChern  my simpledet commit id is ab42b3efb4f54712754e4f2e59f648e231645ad7;I reproduce the hang when roidb is 419341.

**Comment by dl19940602** [comment]
ab42b3efb4f54712754e4f2e59f648e231645ad7   @RogerChern

**Comment by dl19940602** [comment]
@RogerChern Tubtao ,I rebuild my training environment,and i want to try again,could you tell me how to save training params at iter 50000, not iter 59900？

**Comment by RogerChern** [comment]
@dl19940602, 
Currently, the trainer saves the model when each epoch ends, I will try to push a patch today to allow save checkpoint at a certain step.

**Comment by dl19940602** [comment]
@RogerChern  ok ,please tell me later,Thank you!

**Comment by RogerChern** [comment]
@dl19940602,

With #189, add the last two lines of codes in your config and you should be able to save a checkpoint at the 50k iteration.

```
    class ModelParam:
        train_symbol = train_sym
        test_symbol = test_sym
        rpn_test_symbol = rpn_test_sym

        from_scratch = False
        random = True
        memonger = False
        memonger_until = "stage3_unit21_plus"

        class pretrain:
            prefix = "pretrain_model/resnet-50"
            epoch = 0
            fixed_param = ["conv0", "stage1", "gamma", "beta"]

        from utils.callback import do_checkpoint_iter
        batch_end_callbacks = [do_checkpoint_iter("experiments/{}/checkpoint".format(General.name), 50000)]
```

**Comment by dl19940602** [comment]
@RogerChern  Yuntao ,could you tell me your training environment? May it be problem of my training envs?

**Comment by RogerChern** [comment]
I am always using the latest docker provided in the INSTALL.md. And my
hardware environment is 8X 1080Ti and 2X E5-2682v4.

**Comment by dl19940602** [comment]
@RogerChern ok, Now that i meet the hang at iter 59900, could i save the epoch at iter 59000,and reload the taining sample at next epoch? Then where should i modify?

**Comment by RogerChern** [comment]
@dl19940602,
Although I am still quite confused about why the hang happens, I think you may resolve it by changing the `<=` to `<` in L694. The loader now will discard the last batch.

https://github.com/TuSimple/simpledet/blob/7da1d59d18d47531009fac7ef27e371953583c80/core/detection_input.py#L693-L694

**Comment by RogerChern** [comment]
The most likely reason for the hang is that some worker died handling some specific record, maybe due to the image does not exist or something else. And in turn, the collector can not get a full batch and just hangs there forever.

**Comment by RogerChern** [comment]
Hi @dl19940602 ,
Any updates on this issue?

**Comment by dl19940602** [comment]
@RogerChern Hi Yuntao, thank you for help me with my problem, i find that this hang may caused by my training environment, I tried in cloud server, i can finish an epoch normally, i will close the issue soon, thank you very much!

**Comment by RogerChern** [comment]
@dl19940602 
Glad to see the problem finally solved. 
This may be caused by some silent file corruption on the disk, I will try to add some checks to alert the user for this.
