### ISSUE TITLE
TridentNet for Transfer Learning?

### ISSUE THREAD

**Issue by mistaleee** [TuSimple/simpledet#186]
Hello all, 
I found TridentNet on the following survey: https://paperswithcode.com/sota/object-detection-on-coco 

I´m new to the field of deep learning, but I would like to use the TridentNet for an industry use case. Therefore I have a dataset consisting of 2500 images and annotations (PASCAL VOC format). 

Can I use TridentNet for Transfer Learning on my own custom dataset?

I´d really be happy, if someone could shortly describe if this is possible and if so, which main steps have to be done to achieve Transfer Learning of TridentNet to a custom dataset.

Thanks.
Alice

**Comment by RogerChern** [comment]
Please refer to #146 and do not hesitate to ask if more details are needed.

**Comment by mistaleee** [comment]
Thanks for the quick reply. I follow the suggestions in the linked issue.

**Comment by mistaleee** [comment]
@RogerChern indeed, there is something I couldn`t figure out so far. In the issue #146  XuShoweR mentioned that there should exist a file called experiments/model/model_0018.params. I ran the script detection_train.py with the parameter --config config/tridentnet_r101v2c4_c5_2x.py and it crashed, telling me that this file is missing:

**Comment by RogerChern** [comment]
@mistaleee , unzip this [model](https://simpledet-model.oss-cn-beijing.aliyuncs.com/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.zip). Details are included in [here](https://github.com/TuSimple/simpledet/tree/master/models/tridentnet).

**Comment by mistaleee** [comment]
Great, the model was loaded. Unfortunately, there is another problem now:

`08-06 20:38:38 Can not find stage3_unit2_bn2_shared0_moving_mean,` 
`skipping Traceback (most recent call last):
  File "detection_train.py", line 276, in <module>
    train_net(parse_args())
  File "detection_train.py", line 139, in train_net
    sym, arg_params, aux_params = merge_bn(sym, arg_params, aux_params)
  File "/home/utils/graph_optimize.py", line 77, in merge_bn
    gamma = mx.sym.var(node_name + "_gamma", shape=args[node_name + "_gamma"].shape)`

`KeyError: 'stage3_unit2_bn2_shared0_gamma'
terminate called without an active exception
[1]    5615 abort (core dumped)` 

`python3 detection_train.py --config config/tridentnet_r101v2c4_c5_2x.py`

**Comment by RogerChern** [comment]
It seems you are trying to load the model with fixed bn. Due to the model is trained on a very early version of SimpleDet, it is not compatible with the new computation graph optimization feature. Comment out the following lines and the model should run.

https://github.com/TuSimple/simpledet/blob/ff8f76092c910c0081b3eaf0580be00f7af3ed69/detection_train.py#L137-L139

**Comment by mistaleee** [comment]
After setting the gpu in the config file, training started. Thanks for your fast and effective help!
