### ISSUE TITLE
AttributeError: module 'mxnet.symbol.contrib' has no attribute 'Proposal_v2'

### ISSUE THREAD

**Issue by SimpleXP** [TuSimple/simpledet#188]
Hi,

I know there are closed issues about this error. I checked them all and I still feel like I'm doing nothing wrong here.

I have successfully install simpledet on Ubuntu 16.04 and starting to train my own network. Now I have a new workstation running 18.04, so I decide to move my work to the new workstation.
I did exactly the same when I install the simpledet, including cudnn, nccl, coco-api, you name it.
After I finished installing everything, I use the "python3 detection_train.py --config config/xxxxxx.py" command to train the network, I got this error:

[Warning] Your mxnet does not support ProposalTarget
[Warning] Your mxnet does not support BBoxNorm
[Warning] Your mxnet does not support FocalLoss
Traceback (most recent call last):
  File "detection_train.py", line 276, in <module>
    train_net(parse_args())
  File "detection_train.py", line 21, in train_net
    transform, data_name, label_name, metric_list = config.get_config(is_train=True)
  File "/home/xingpeng/Project/Tattoo_Detection/simpledet/config/tridentnet_r101v2c4_c5_1x.py", line 133, in get_config
    num_branch=Trident.num_branch, scaleaware=Trident.train_scaleaware)
  File "/home/xingpeng/Project/Tattoo_Detection/simpledet/models/tridentnet/builder.py", line 86, in get_train_symbol
    proposal, bbox_cls, bbox_target, bbox_weight = rpn_head.get_sampled_proposal_with_filter(rpn_feat, gt_bbox, im_info, valid_ranges)
  File "/home/xingpeng/Project/Tattoo_Detection/simpledet/models/tridentnet/builder.py", line 279, in get_sampled_proposal_with_filter
    (proposal, proposal_score) = self.get_all_proposal_with_filter(conv_feat, im_info, valid_ranges)
  File "/home/xingpeng/Project/Tattoo_Detection/simpledet/models/tridentnet/builder.py", line 239, in get_all_proposal_with_filter
    proposal = mx.sym.contrib.Proposal_v2(
AttributeError: module 'mxnet.symbol.contrib' has no attribute 'Proposal_v2'

I believe I install and config the mxnet correctly as instructed in the INSTALL.md: Install from Scrach (https://github.com/TuSimple/simpledet/blob/master/doc/INSTALL.md#setup-from-scratch)
Would it be due to the system version problem? Is MXNET not support Ubuntu 18.04 yet?

Thanks in advance and expecting some solution.

**Comment by RogerChern** [comment]
The warning should be quite clear that you did not set up the MXNet properly. Maybe you can try the docker image if you are not a guru with compiling in Linux system.

```
[Warning] Your mxnet does not support ProposalTarget
[Warning] Your mxnet does not support BBoxNorm
[Warning] Your mxnet does not support FocalLoss
```
