### ISSUE TITLE
Training stopped without notification

### ISSUE THREAD

**Issue by DayChan** [TuSimple/simpledet#19]
I used nvidia-docker to run the code, and this is the output.

```bash
02-17 23:40:30 Epoch[0] Batch [9540]    Speed: 18.53 samples/sec        Train-RpnAcc=0.958210,  RpnL1=0.420432, RcnnAcc=0.871656,       RcnnL1=1.303369,
02-17 23:40:42 Epoch[0] Batch [9550]    Speed: 13.73 samples/sec        Train-RpnAcc=0.958218,  RpnL1=0.420353, RcnnAcc=0.871662,       RcnnL1=1.303065,
02-17 23:41:00 Epoch[0] Batch [9560]    Speed: 8.70 samples/sec Train-RpnAcc=0.958227,  RpnL1=0.420287, RcnnAcc=0.871672,       RcnnL1=1.302830,
02-17 23:41:09 Epoch[0] Batch [9570]    Speed: 17.01 samples/sec        Train-RpnAcc=0.958238,  RpnL1=0.420242, RcnnAcc=0.871690,       RcnnL1=1.302588,
root@1e2726dafa6a /o/i/u/d/simpledet# 
```

My training used config `tridentnet_r50v2c4_c5_1x` which was set to train for 6 epochs with coco2014. But it stopped at `Epoch[0]` and didn't print any information.

Additionally, I found  in `./deteciton_train.py: 213`, in `mod.fit` func, the param `num_epoch=end_epoch`, is it configured right?

**Comment by xchani** [comment]
All the config files should work well. Can you reproduce this issue, and provide more information? Make sure your program is not conflict with others.

**Comment by DayChan** [comment]
OK, I try to train for a second time.

**Comment by DayChan** [comment]
@xchani It seems the problem has disappeared, it successfully run through the whole epoch and saved the weight.

**Comment by dl19940602** [comment]
@DayChan I meet the same problem,could you tell me how to solve it ? Thank you !
