### ISSUE TITLE
Error in make.  recipe for target 'group_norm_helper_gpu.o' failed

### ISSUE THREAD

**Issue by SimpleXP** [TuSimple/simpledet#193]
Hi,

When I try to install from scratch, I encounter this error:

src/operator/contrib/group_norm_helper.cu(332): error: namespace "std" has no member "accumulate"

src/operator/contrib/group_norm_helper.cu(333): error: namespace "std" has no member "accumulate"

2 errors detected in the compilation of "/tmp/tmpxft_0000049a_00000000-8_group_norm_helper.compute_70.cpp1.ii".
Makefile:544: recipe for target 'build/src/operator/contrib/group_norm_helper_gpu.o' failed
make: *** [build/src/operator/contrib/group_norm_helper_gpu.o] Error 1
make: *** Waiting for unfinished jobs....

Could you advise what should I do to solve it?
Thanks in advance.

**Comment by SimpleXP** [comment]
Is it because the gcc version?
My gcc version is 7.4.
I have successfully install simpledet in another workstation, the gcc version is 5.4.

**Comment by RogerChern** [comment]
Your guess is reasonable. We only tested the compiling on Ubuntu 16.04 which is bundled with gcc 5.4.
