### ISSUE TITLE
does simpledet support windows?

### ISSUE THREAD

**Issue by goodtogood** [TuSimple/simpledet#2]
Hi,
   does cxx op of simpledet support windows?
thanks

**Comment by RogerChern** [comment]
Everything except SyncBatchNorm and SyncInplaceABN should work just fine on windows. Although the synchronization of these ops is written in standard cpp, we never test them on a platform other than Linux. Please refer to [install MXNet on Windows](http://mxnet.incubator.apache.org/versions/master/install/windows_setup.html) for more information.

**Comment by goodtogood** [comment]
@RogerChern 
got it . I'll have  a try.
thanks.
