### ISSUE TITLE
mxnet install 

### ISSUE THREAD

**Issue by hxy1181501030** [TuSimple/simpledet#20]
The code in 'incubator-mxnet-master' has been recompiled sucessfully according to ' Setup from Scratch' in the '`INSTALL.md' file after "make -j4",  and libmxnet.so  libmxnet.a has been created, but after the 
''cd python
python3 setup.py install '' , and run the simpledet code,it shows 
"AttributeError: module 'mxnet.symbol.contrib' has no attribute 'ROIAlign_v2' "   
I have run the commad "grep -r contrib.ROIAlign_v2",it has been find in libmxnet.so  libmxnet.a.
Is there any modification in  "incubator-mxnet-master/python"?

**Comment by queryor** [comment]
i meet the same problem.

**Comment by xchani** [comment]
We didn't modify any file in mxnet except adding operators. Could you try ```python3 -c "import mxnet as mx; print(mx.__file__)"```, and make sure you import mxnet from the right directory.

**Comment by hxy1181501030** [comment]
@xchani   i have run the 'python3 -c "import mxnet as mx; print(mx.__file__)" ', the result is  "/home/research/.local/lib/python3.5/site-packages/mxnet/__init__.py".  should i change it? and how to change it?

**Comment by RogerChern** [comment]
@hxy1181501030 Checkout your `PYTHONPATH`. If you installed mxnet from scratch with `python3 setup install.py`, it should reside in `/usr/local/lib` than `~/.local`.

**Comment by queryor** [comment]
@RogerChern  i use the python with anaconda, so the mx.__file__ is "/home/qyj/anaconda3/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/__init__.py". is it right？why should reside in '/usr/local/lib'?

**Comment by RogerChern** [comment]
Sorry for the late reply. This should be some nasty PATH or PYTHONPATH environment variable problem. Could you please provide the output of `env` in your shell. Or you can try out the pre-built docker or singularity images.

**Comment by queryor** [comment]
this is my env.i didn't see the $pythonpath,should i set it?
`USER=qyj
LOGNAME=qyj
HOME=/home/qyj
PATH=/home/qyj/anaconda3/envs/pytorch/bin:/usr/local/cuda-9.0/bin::/home/qyj/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
MAIL=/var/mail/qyj
SHELL=/usr/bin/zsh
SSH_CLIENT=192.168.1.136 59308 22
SSH_CONNECTION=192.168.1.136 59308 192.168.1.89 22
SSH_TTY=/dev/pts/0
TERM=xterm
DISPLAY=localhost:11.0
XDG_SESSION_ID=115
XDG_RUNTIME_DIR=/run/user/1005
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
LC_NUMERIC=zh_CN
LC_TIME=zh_CN
LC_MONETARY=zh_CN
LC_PAPER=zh_CN
LC_NAME=zh_CN
LC_ADDRESS=zh_CN
LC_TELEPHONE=zh_CN
LC_MEASUREMENT=zh_CN
LC_IDENTIFICATION=zh_CN
SHLVL=1
PWD=/home/qyj
OLDPWD=/home/qyj/mxnet
ZSH=/home/qyj/.oh-my-zsh
LD_LIBRARY_PATH=/home/qyj/project/mkl-dnn/build/src/:/home/qyj/incubator-mxnet/lib/
PAGER=less
LESS=-R
LC_CTYPE=zh_CN.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
CONDA_SHLVL=1
CONDA_DEFAULT_ENV=pytorch
CONDA_EXE=/home/qyj/anaconda3/bin/conda
CONDA_PREFIX=/home/qyj/anaconda3/envs/pytorch
CONDA_PROMPT_MODIFIER=(pytorch)
CONDA_PYTHON_EXE=/home/qyj/anaconda3/bin/python
_=/usr/bin/env
`

**Comment by RogerChern** [comment]
@queryor Your path looks fine to me. Did you accidentally forget to copy operators in `operator_cxx` to `mxnet/src/operator`?

**Comment by queryor** [comment]
@RogerChern i am sure i have copy this directories to  `mxnet/src/operator`.

**Comment by suyz526** [comment]
@queryor 
If you have installed it correctly, mxnet.__version__ should be 1.5.0.

**Comment by Caius-Lu** [comment]
> The code in 'incubator-mxnet-master' has been recompiled sucessfully according to ' Setup from Scratch' in the '`INSTALL.md' file after "make -j4", and libmxnet.so libmxnet.a has been created, but after the
> ''cd python
> python3 setup.py install '' , and run the simpledet code,it shows
> "AttributeError: module 'mxnet.symbol.contrib' has no attribute 'ROIAlign_v2' "
> I have run the commad "grep -r contrib.ROIAlign_v2",it has been find in libmxnet.so libmxnet.a.
> Is there any modification in "incubator-mxnet-master/python"?
Can you tell how to install contrib.ROIAlign v2, I have met this problem too.
