### ISSUE TITLE
detection speed is slower than the training speed

### ISSUE THREAD

**Issue by 15122901359** [TuSimple/simpledet#203]
Hello, I would like to ask why the detection speed is slower than the training speed? I used detection infer speed.py to test the trained models including cascade, tridentnet, retinanet and other detection networks. It is found that the test speed is obviously lower than the training speed, can you help to answer it?
detection_infer_speed.py --config config/cascade_r50v1_fpn_1x.py --shape 800 800 95.20783424377441 
cascade_r50v1_fpn_1x.py FP16
train speed 15.02 samples/s

**Comment by RogerChern** [comment]
For training, you are using 8 GPUs.

**Comment by 15122901359** [comment]
> For training, you are using 8 GPUs.
 @RogerChern Thank you very much for your reply.I used the same configuration which was using 2 GPUs for both training and testing

**Comment by RogerChern** [comment]
@15122901359 
`detection_infer_speed.py` measures the latency of the detector on a single card.

**Comment by 15122901359** [comment]
I've got it,thanks again for your reply about this problem.
