### ISSUE TITLE
What is the param in subsample_proposal mean?

### ISSUE THREAD

**Issue by DayChan** [TuSimple/simpledet#21]
I desire to know what is the meaning of param `proposal_wo_gt`, `fg_fraction`, `fg_thr`, `bg_thr_hi` and `bg_thr_lo` in `RpnParam.subsample_proposal`.

Addtinally, what is class Neck mean? It seems doesn't do anything in code.
```python
class Neck(object):
    def __init__(self, pNeck):
        self.pNeck = pNeck

    def get_rpn_feature(self, rpn_feat):
        return rpn_feat

    def get_rcnn_feature(self, rcnn_feat):
        return rcnn_feat
```
Is it a structure in Faster R-CNN?

**Comment by xchani** [comment]
- ```proposal_wo_gt```: whether append ground truth to proposal in ```proposal_target``` layer
- ```fg_fraction```: foreground fraction
- ```fg_thr```: threshold for foreground
- ```bg_thr_hi```, ```bg_thr_lo```: highest and lowest threshold for background

The usage of neck is declared in [README](https://github.com/TuSimple/simpledet_internal#how-is-faster-rcnn-built). This design is prepared for more flexible feature extraction, and can be ignored in Faster R-CNN.

**Comment by DayChan** [comment]
Thanks
