### ISSUE TITLE
proposal_layer 

### ISSUE THREAD

**Issue by machinelear** [TuSimple/simpledet#222]
simpledet/operator_cxx/contrib/proposal_layer.cc
 workspace_proposals[n][index][4] = scores[n][i + width * height * num_anchors][j][k]; in 373 line
.Why is this channels "i + width * height * num_anchors" instead of "i+num_anchors"?

**Comment by RogerChern** [comment]
the .cc file is outdated. Please check the .cu implementation.

**Comment by machinelear** [comment]
Thanks!
