### ISSUE TITLE
When installing cocoapi, it fails with gcc error

### ISSUE THREAD

**Issue by wmmxk** [TuSimple/simpledet#223]
The version of my gcc is 7.4 on a ubuntu 18.04.1. When I run pip install 'git+https://github.com/RogerChern/cocoapi.git#subdirectory=PythonAPI'. I run into this error: 

gcc: error: pycocotools/_mask.c: No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools

I googled the error and found the following [solution.](https://github.com/scrapy/scrapy/issues/2115). I installed the following libs, now it works. 
sudo apt-get install python3 python-dev python3-dev \
     build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev \
     python-pip

**Comment by RogerChern** [comment]
Try the official cocoapi repo?
```
pip3 install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
```

**Comment by shouwangzhe134** [comment]
sudo apt-get install cython
