### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by surserrr** [TuSimple/simpledet#225]
I just follow the install and meet an error:

-------------------------------------------------------------------------------------------
Install
We provide a local installation here for Debian/Ubuntu system. To use a pre-built docker or singularity images, please refer to INSTALL.md for more information.

install dependency
sudo apt update && sudo apt install -y git wget make python3-dev libglib2.0-0 libsm6 libxext6 libxrender-dev unzip

install python dependency
pip3 install 'matplotlib<3.1' opencv-python pytz --user

download and intall pre-built wheel for CUDA 10.0
check INSTALL.md for wheels for other CUDA version
wget https://bit.ly/2jRGqdc -O mxnet_cu100-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl
pip3 install mxnet_cu100-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl --user

install pycocotools
pip3 install 'git+https://github.com/RogerChern/cocoapi.git#subdirectory=PythonAPI' --user

install mxnext, a wrapper around MXNet symbolic API
pip3 install 'git+https://github.com/RogerChern/mxnext#egg=mxnext' --user

get simpledet
git clone https://github.com/tusimple/simpledet
cd simpledet
make

test simpledet installation
mkdir -p experiments/faster_r50v1_fpn_1x
python3 detection_infer_speed.py --config config/faster_r50v1_fpn_1x.py --shape 800 1333
If the last line execute successfully, the average running speed of Faster R-CNN R-50 FPN will be reported. And you have successfuly setup SimpleDet. Now you can head up to the next section to prepare your dataset.

-----------------------------------------------------------------------------------------------------------

**OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory.**

**Comment by louielu1027** [comment]
you CUDA lib path is not right.
DO this command:
export LD_LIBRARY_PATH=/your/cuda/lib64/:/your/cuda/lib64/stubs:$LD_LIBRARY_PATH
