### ISSUE TITLE
some question about config/tridentnet_r101v2c4_c5_addminival_2x.py

### ISSUE THREAD

**Issue by mrbulb** [TuSimple/simpledet#23]
in `config/tridentnet_r101v2c4_c5_addminival_2x.py`, the `DatasetParam.image_set` is defined as follow
https://github.com/TuSimple/simpledet/blob/30b658cb4ae38b77b14bb27135157d09ab34fa9d/config/tridentnet_r101v2c4_c5_addminival_2x.py#L119

but in `utils/generate_roidb.py`, there are no mapping to `testdev2017_gt_roidb` 
https://github.com/TuSimple/simpledet/blob/7d1b95901997912f10c99eb2e4b4b39ff028509e/utils/generate_roidb.py#L15
so that you can't genenrate `COCO_testdev2017_gt_roidb.roidb` 

and this will cause error when you use `config/tridentnet_r101v2c4_c5_addminival_2x.py` to train/test when searching for roidb in here 
https://github.com/TuSimple/simpledet/blob/7d1b95901997912f10c99eb2e4b4b39ff028509e/detection_test.py#L39

so i think may be just change to 
```python
image_set = ("coco_test-dev2017", )
```
can solve this problem

**Comment by xchani** [comment]
Thanks for reporting this mistake, we create a pr #24 to fix this.

**Comment by mrbulb** [comment]
Thanks for fixing the mistake so quickly!
