### ISSUE TITLE
Is there possibility to use gradient batch aggregation for big models with small amount of GPUs?

### ISSUE THREAD

**Issue by InfiniteLife** [TuSimple/simpledet#230]
For example we have 2 GPU for training and each fits batch of 2 making effective batch size 4. If there is gradient batch aggregation we could process several batches on each GPU and aggregate gradients by that increasing effective batch size. Is there possibility to use such feature?

**Comment by RogerChern** [comment]
Is gradient aggregation required for small number of GPUs? In my
experience, bs=8 or bs=16 makes no difference with linear lr.
