### ISSUE TITLE
Optimizer/ Solver

### ISSUE THREAD

**Issue by mistaleee** [TuSimple/simpledet#234]
Hi all,

I've been searching for while to get to know which solver/optimizer (e.g. gradient descent, Adam etc. ) Trident is actually using.

Can anybody give me a hint how I can change the solver?

Thanks.

**Comment by RogerChern** [comment]
https://github.com/TuSimple/simpledet/blob/dd4eb159cf3934b949a89b745f00ddc62c0745c9/config/tridentnet_r50v1c4_c5_1x.py#L158-L160

**Comment by mistaleee** [comment]
Thanks. Which solvers would be accepted instead of sdg?

**Comment by xchani** [comment]
Check this https://mxnet.incubator.apache.org/api/python/docs/api/gluon-related/mxnet.optimizer.html .
Remember to use lowercase of these names, i.e. sgd, adam, nag, etc.

**Comment by mistaleee** [comment]
Thanks @xchani
