### ISSUE TITLE
Any plan to support DeformableConvolution and DeformablePSROIPooling?

### ISSUE THREAD

**Issue by ACkuku** [TuSimple/simpledet#240]
Official MxNet [DeformablePSROIPooling](http://mxnet.incubator.apache.org/api/python/docs/api/ndarray/_autogen/mxnet.ndarray.contrib.DeformablePSROIPooling.html?highlight=deformablepsroipooling#mxnet.ndarray.contrib.DeformablePSROIPooling) accept rois is 2D array[[batch_index, x1, y1, x2, y2]], and simpledet rois(proposals) is 3D array, how to solve this? Thanks~

**Comment by huangzehao** [comment]
Note batch_image=B, image_roi=N, then the shape of simpledet rois is [B, N, 4]. You can convert [B, N, 4] into [B*N, 5] by the following codes: 
`
B = 10
N = 5
rois = mx.nd.ones((B, N, 4))
rois = mx.nd.reshape(rois, (-1, 4))
batch_ind = mx.nd.arange(B)
batch_ind = mx.nd.repeat(batch_ind, N)
batch_ind = mx.nd.expand_dims(batch_ind, axis=-1)
rois = mx.nd.concat(batch_ind, rois, dim=1)
`

**Comment by ACkuku** [comment]
thank you very much~
