### ISSUE TITLE
scratch/tridentnet_2x，能复现ImageNet pre-training的结果吗？

### ISSUE THREAD

**Issue by YaqiLYU** [TuSimple/simpledet#242]
1. config/scratch/tridentnet_r50v1bc4_c5_syncbn_scratch_2x.py用了2x，但《Rethinking ImageNet Pre-training》说6x才能获得与pre-training相当的结果。那这一config能获得什么pre-training相似的AP吗？如果能，是因为larger learning rate吗？
2. Preparing Data只有val2017，但所有config测试都用minival2014，这两者是否相同？如果不同，哪里可以下载minval2014.
非常感谢。

**Comment by RogerChern** [comment]
Please use English or English + other languages when reporting an issue.
Reading text not written in your mother tongue is quite hard, e.g.
قراءة النص غير المكتوب بلغتك الأم صعبة للغاية

As for your question.
1. ImageNet pretraining is necessary for SOTA performance on COCO. Take a look at the models with the gluon resnet_v1b pretraining.
But ditching the pretraining models gives us 
- a much broader choice of backbones, like the EfficientNet
- a fair comparison between different models, especially when implemented in different frameworks.

2. val2017 is simply a rename of minival2014.
