### ISSUE TITLE
[BUG] Bug in json_to_roidb.py and fixed

### ISSUE THREAD

**Issue by xiaosongshine** [TuSimple/simpledet#245]
**Describe the bug**
code in line 12-13
```python
 parser.parse_args()
 return parser.json
```
are supossed to be change into 
```python
arg = parser.parse_args()
return arg.json
```
or you wil get 

> AttributeError: 'ArgumentParser' object has no attribute 'json'

**Comment by RogerChern** [comment]
Thanks for bringing this up. Would you mind make a PR?

**Comment by xiaosongshine** [comment]
> Thanks for bringing this up. Would you mind make a PR?

Ok, I will do it later..
