### ISSUE TITLE
Can't download pretrained model

### ISSUE THREAD

**Issue by dneirfi** [TuSimple/simpledet#251]
Hi. I can't download pretrained model in MODEL_ZOO.
When I click the link named model such as resnet50_v1b , It returns error.
How can I download it? 
Anyone help me!!!

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>
You have no right to access this object because of bucket acl.
</Message>
<RequestId>5DB1EB1731333D32388BD7DA</RequestId>
<HostId>simpledet-model.oss-cn-beijing.aliyuncs.com</HostId>
</Error>

**Comment by RogerChern** [comment]
Confirmed. We are looking into it right now.

**Comment by dneirfi** [comment]
How long it will take?
When can I download it?

**Comment by RogerChern** [comment]
fixed by #253
