### ISSUE TITLE
threshold for foreground in metric

### ISSUE THREAD

**Issue by edwardyangxin** [TuSimple/simpledet#265]
For retinanet, I see there's only one metric available which is Foreground acc:
![image](https://user-images.githubusercontent.com/13101725/70126475-11fdee00-16b4-11ea-9942-0e55fe3239ec.png)
my question is: why you treat all anchor as foreground? what is a rational threshold for foreground?
I'm training on a nuclei dataset and I only have 1 foreground class which is "Positive". In my situation, it seems its never learning here.

**Comment by RogerChern** [comment]
We only measure the accuracy of foreground anchors since they are scarce.
We did not treat  all anchors as foreground.

**Comment by edwardyangxin** [comment]
thanks for your quick reply:)
I don't know if I get it right. For my situation, with only 1 foreground class, I can set threshold parameter as 0.5 for calculating accuracy metric.  Is it a rational choice? Otherwise, I always get 100% accuracy:(

**Comment by RogerChern** [comment]
If you **use** all the detected after NMS with a score >= 0.5, then 0.5 is
a good threshold.
For the COCO dataset, we evaluate all boxes with scores >= 0.05, so the
threshold is 0.05.
