### ISSUE TITLE
Why normalize step not found in preprocess function?

### ISSUE THREAD

**Issue by cosimo17** [TuSimple/simpledet#267]
I find there is no normalize step in preprocess function. why input image can be feed to network with out normalize?

**Comment by RogerChern** [comment]
Both training and testing have normalization. They are done in the loader. See L248 and L263.

https://github.com/TuSimple/simpledet/blob/dafc5536d2ed74094872348801493e42ccaa3c53/config/faster_r50v1_fpn_1x.py#L245-L269
