### ISSUE TITLE
some question about pretrained_model

### ISSUE THREAD

**Issue by mrbulb** [TuSimple/simpledet#27]
In training step, it seems need pretraind model to train.
I'm a freshman to mxnet and don't know how to get this pretraind model.
Wound you mind give the download link of this pretrained model?

**Comment by neophack** [comment]
https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md

**Comment by mrbulb** [comment]
Oh, Thanks, I didn't mention the pretraind model on the top
