### ISSUE TITLE
Cannot train detector with only one category

### ISSUE THREAD

**Issue by loki900718** [TuSimple/simpledet#273]
Thanks for the great work. I have successfully trained a detector for a larger dataset that contains 6 categories of objects. But when I moved to a smaller dataset with only one category, FGAccMetric (since I'm using RetinaNet) always shows 1.0 during training, but the detector cannot detect anything during testing. I tried increasing the foreground threshold to above 0, but then the metric would always be very close to 0. Have no clue what's going on here.

**Comment by xchani** [comment]
It doesn't make any sense. I once trained RetinaNet as RPN, also with only one class. Can you try to reduce the learning rate?
Perhaps we could rewrite focal loss and replace FGAccMetric. @RogerChern
