### ISSUE TITLE
RetinaNet with input size 1024*1024

### ISSUE THREAD

**Issue by edwardyangxin** [TuSimple/simpledet#276]
after I change input size to 1024 by 1024:
    class ResizeParam:
        short = 1024
        long = 1024
    class PadParam:
        short = 1024
        long = 1024

I got train error: 
![image](https://user-images.githubusercontent.com/13101725/70848976-d6cd9d00-1eb3-11ea-8baf-975e92fce4c5.png)

after I change back to 800*1333, it's ok. How can I correctly set the input size params?

**Comment by edwardyangxin** [comment]
After change anchor params, it works. So I close the issue here:)
![image](https://user-images.githubusercontent.com/13101725/70849231-7ab84800-1eb6-11ea-8584-518e8c2f1911.png)

**Comment by RogerChern** [comment]
Sorry for the inconvenience, we shall make the anchor adaptive to image size
