### ISSUE TITLE
License issues/conflicts!

### ISSUE THREAD

**Issue by jpizarrom** [TuSimple/simpledet#280]
There is a license file https://github.com/TuSimple/simpledet/blob/master/LICENSE But in the readme says "This project is release under the Apache 2.0 license for non-commercial usage. For commercial usage, please contact us for another license."

I understand that an Apache 2.0 permits commercial use.What does "For commercial usage, please contact us for another license." means?

Thanks

**Comment by RogerChern** [comment]
Dual licensing is quite common for open source projects.
The core idea behind dual-licensing is that the community HAS NO obligation
to provide any form of support for commercial usage.

**Comment by jpizarrom** [comment]
I want to know if I am allow to develop a commercial app using simpledet. I suppose the Apache 2.0 license give permit to do that.

Is that right?

**Comment by RogerChern** [comment]
Yes. As a matter of fact, NO popular licenses restrict commercial usage of
open source projects.

**Comment by jpizarrom** [comment]
"As a permissive license, the Apache 2.0 license does not prevent extra restrictions"  https://opensource.stackexchange.com/a/7401

**Comment by RogerChern** [comment]
Well, not quite a license lawyer myself. But I am aware of there are many
open source projects like Qt, MongoDB are dual licensed.

And I am closing the issue due to it is way off-topic.

**Comment by jpizarrom** [comment]
"The freedom to run the program for any purpose" in https://www.qt.io/faq/, it include commercial and non-commercial

They use dual license in different way.
