### ISSUE TITLE
python detection_test.py --config config/tridentnet_r101v1c4_c5_1x.py

### ISSUE THREAD

**Issue by chenmw269** [TuSimple/simpledet#281]
I test it many time, but the results were very bad, the AP result is around 0.001, I don't know why.my annotation flie is right, but tridentnet can't read all my pictures in test. I test about 3000 images, but the net only test about two dozen images. Is there something wrong with that part?
![图片](https://user-images.githubusercontent.com/57318837/71331391-eeb8b700-256c-11ea-99e3-26839248a144.png)
![图片](https://user-images.githubusercontent.com/57318837/71331415-114ad000-256d-11ea-9ec5-71ef79cb1e0f.png)

**Comment by RogerChern** [comment]
Could you please share more info of your customary json annotations?

**Comment by chenmw269** [comment]
![图片](https://user-images.githubusercontent.com/57318837/71339889-d6a65f00-258f-11ea-909e-14e2f925c714.png)
 The data format for the annotation file looks like this, I've only cut a part of it.

**Comment by RogerChern** [comment]
You image filed in the json file only contains dozens of pics. That’s the
problem.

**Comment by chenmw269** [comment]
I just selected a part to show you .The actual data is about 3000 images. I want you to see if there are any errors in the data format

**Comment by chenmw269** [comment]
The format of my annotation flie : {''categories'':[{ id,name }], ''images'':[{ width,height,id,file_name}], ''info'':{ }, ''annotations'':[{ iscrowd, image_id, category_name, category_id, bbox, area, segmentation, id}]} This is the frame of my file and the data in it. Do I have any messing data?

**Comment by RogerChern** [comment]
I see. You image id is too big which exceeds the range of float32 type.

**Comment by RogerChern** [comment]
This is a caveat of MXNet which forces all input of a graph to have the same data type. I will try to fix it by introducing some mapping between float32 and int32.

**Comment by chenmw269** [comment]
Ok, I'll try changing the id, try testing again. thanks! But the type of annotation file format I use for training and testing is the same. when I was training, the id is the same length, I can train the model, It's just the problem I mentioned above that when I test. So is it just the reason you mentioned above, or are there some other reasons?

**Comment by RogerChern** [comment]
Training does not use the image id field. The image ids are responsible for
pairing detection results with the test annotation. For training, the label
and image are always paired so image ids are not used

**Comment by chenmw269** [comment]
Ok, I understand. I'll test it the way you said, Thank you so much for your patience！
