### ISSUE TITLE
How to measure the inference time of the int8 quantified model?

### ISSUE THREAD

**Issue by DuZzzs** [TuSimple/simpledet#283]
Thank you for your work. When I reproduce the int8 quantified example, how do I get the inference time of the int8 quantized model? I ran detection_test.py and did not observe speedups. Run a file? Does anyone know? Thanks.

This table: ( https://github.com/TuSimple/simpledet/tree/master/config/int8)
| dtype | time(ms) | minival mAP|
| ----- | -------- | -----------|
| fp32  | 260      | 35.7       |
| int8  | 100      | 35.8       |

my environment:
gpu : 2060
tensorrt 7.0

**Comment by RogerChern** [comment]
The inference time is measured on an internal platform based on trt. The
INT8 quantization training will give you an INT8 model, but the inference
software stack is beyond the current scope of SimpletDet.

**Comment by DuZzzs** [comment]
I see. Thank you.
