### ISSUE TITLE
Excuse me, is the trident net's anchor setting too sparse?

### ISSUE THREAD

**Issue by YilanWang** [TuSimple/simpledet#288]
I read the source code of tridentnet, and got some confusion. If stride is 16, then the smallest scale anchor (scale = 2) will be located on the feature map with a very sparse distribution. When the area of retinanet or fpn is the smallest (stride=4, scale=8, length=32, regardless of ratio shift), their distribution on P3 is very dense. However, the APs of tridentnet is greater than FPN. How does such an anchor setting affect the results? Many thanks for your answers!

**Comment by RogerChern** [comment]
There are many underlying detector design tradeoffs related. Too be short, adding more small anchors is not very rewarding due to the limited resolution of the raw images in COCO.

**Comment by YilanWang** [comment]
> There are many underlying detector design tradeoffs related. Too be short, adding more small anchors is not very rewarding due to the limited resolution of the raw images in COCO.

Many thanks for your reply! Did you try trident-block in single-stage framework, Can it get good results？

**Comment by RogerChern** [comment]
Some fellow researchers have tried it out on SSD and it worked.

**Comment by YilanWang** [comment]
Cooool!
