### ISSUE TITLE
question about OP proposal_target_v2

### ISSUE THREAD

**Issue by tianxh1212** [TuSimple/simpledet#29]
Thanks for the excellent work. I got an error about op proposal_target_v2 when i am adding mixup to training.would you please give me some advice? 
thanks.
my code(models/tridentnet/builder.py):
![image](https://user-images.githubusercontent.com/16973503/53167693-ad394180-3613-11e9-86bb-ec6a8b93a4aa.png)
![image](https://user-images.githubusercontent.com/16973503/53168367-6c422c80-3615-11e9-8704-eadae58ec10c.png)

i add gt_bbox_mix and aux in the input_record to record the mixup gtbbox and mix weight, and compute loss of both normal gt_bbox_label and gt_bbox_mix_label, at last combine the loss by weight.

when computing the gt_bbox_mix_label, there was an error:

`  File "/ML/tian/simpledet/simpledet_code/core/detection_metric.py", line 50, in update
    pred_label = mx.ndarray.argmax_channel(pred).astype('int32').asnumpy().reshape(-1)
  File "/ML/tian/venv_mxnet/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/ndarray/ndarray.py", line 1972, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/ML/tian/venv_mxnet/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/base.py", line 251, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [06:52:50] src/operator/./proposal_target_v2-inl.h:138: Check failed: req[proposal_target_v2_enum::kRoiOutput] == kWriteTo (0 vs. 1) `

**Comment by RogerChern** [comment]
Sorry for the late reply. This may due to that you did not use `proposal_mix` later in the graph, and the underlying mxnet graph pruned this unused node. You can try to comment out the check at line 138 of `src/operator/./proposal_target_v2-inl.h`.

**Comment by tianxh1212** [comment]
> Sorry for the late reply. This may due to that you did not use `proposal_mix` later in the graph, and the underlying mxnet graph pruned this unused node. You can try to comment out the check at line 138 of `src/operator/./proposal_target_v2-inl.h`.

yes，i actually do not use  `proposal_mix` later in the graph. and the problem
is solved by your suggestion, thanks!
