### ISSUE TITLE
Test time for TridentNet

### ISSUE THREAD

**Issue by botanyldrm** [TuSimple/simpledet#290]
I tried to regenerate results of TridentNet with tridentnet_r101v2c4_c5_1x.py and tridentnet_r101v2c4_c5_fastapprox_1x.py config files over COCO dataset but it take a few hours for RTX2060 gpu. I just didnt understand what is the time consuming part for test evaluation, why it takes too long? I wonder if I have a problem.

**Comment by xchani** [comment]
Please try ```detection_infer_speed.py``` to obtain the inference time of your model, and see the theoritical time needed to go through the whole dataset.

**Comment by botanyldrm** [comment]
> Please try `detection_infer_speed.py` to obtain the inference time of your model, and see the theoritical time needed to go through the whole dataset.

Thanks a lot
