### ISSUE TITLE
使用两块卡训练报错

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#291]
我使用两块2080Ti训练Tridentnet_r50v1c4_c5_1x,训练自己的数据集。
CUDA版本是10.0.13，cudnn版本是7.4.1
安装的Mxnet的版本是：mxnet_cu100-1.6.0b20191214-py2.py3-none-manylinux1_x86_64.whl
设置的使用的显卡编号为：  gpus   = [2,3]
batch_image 已经改为1了：batch_image = 1 if is_train else 1
还是一运行训练代码就报错out of memory
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:27:50] src/storage/./pinned_memory_storage.h:62: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: out of memory
谢谢大佬能指正

**Comment by xchani** [comment]
Could you please try another config, like ```faster_r50v1_fpn_1x```? Does the same error occur?

**Comment by dongzhenguo2016** [comment]
> Could you please try another config, like `faster_r50v1_fpn_1x`? Does the same error occur?
必须得从第0块卡开始使用显卡，比如用第0块卡，或者第0和1块，或者第0和1和2块卡，反正必须从第0块卡开始才能运行起来。很奇怪

**Comment by sjtuytc** [comment]
> > Could you please try another config, like `faster_r50v1_fpn_1x`? Does the same error occur?
> > 必须得从第0块卡开始使用显卡，比如用第0块卡，或者第0和1块，或者第0和1和2块卡，反正必须从第0块卡开始才能运行起来。很奇怪

都是这样的

**Comment by RogerChern** [comment]
Does set the environment variable CUDA_VISIBLE_DEVICES help?
