### ISSUE TITLE
Install error when download and install pre-built wheel for CUDA10.1

### ISSUE THREAD

**Issue by liu-zg15** [TuSimple/simpledet#295]
I am trying to install the simpledet follow the setup.sh.
when I run pip install https://1dv.alarge.space/mxnet_cu101-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl,
following error happens:

> Downloading https://1dv.alarge.space/mxnet_cu101-1.6.0b20191214-py2.py3-none-manylinux1_x86_64.whl (556.0MB)
>      |███████████████████████████████▌| 546.7MB 97kB/s eta 0:01:36ERROR: Exception:
> Traceback (most recent call last):
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
>     yield
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
>     data = self._fp.read(amt) if not fp_closed else b""
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
>     data = self.__fp.read(amt)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/http/client.py", line 457, in read
>     n = self.readinto(b)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/http/client.py", line 501, in readinto
>     n = self.fp.readinto(b)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/ssl.py", line 1071, in recv_into
>     return self.read(nbytes, buffer)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/ssl.py", line 929, in read
>     return self._sslobj.read(len, buffer)
> ConnectionResetError: [Errno 104] Connection reset by peer
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
>     status = self.run(options, args)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
>     resolver.resolve(requirement_set)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
>     self._resolve_one(requirement_set, req)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
>     abstract_dist = self._get_abstract_dist_for(req_to_install)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
>     req, self.session, self.finder, self.require_hashes
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
>     progress_bar=self.progress_bar
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/download.py", line 465, in unpack_url
>     progress_bar=progress_bar
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
>     progress_bar)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/download.py", line 551, in _download_http_url
>     _download_url(resp, link, content_file, hashes, progress_bar)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/download.py", line 255, in _download_url
>     consume(downloaded_chunks)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 641, in consume
>     deque(iterator, maxlen=0)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/download.py", line 223, in written_chunks
>     for chunk in chunks:
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 160, in iter
>     for x in it:
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_internal/download.py", line 212, in resp_read
>     decode_content=False):
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/contextlib.py", line 130, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/gone/anaconda3/envs/simpledet/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
>     raise ProtocolError("Connection broken: %r" % e, e)
> pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
> 
I guess it's caused by the server of the whl.
Is that correct?
Any solutions for this situation?
My system is ubuntu 16.04.

**Comment by huangzehao** [comment]
Hi, can you try download this wheel and then install?

**Comment by dongzhenguo2016** [comment]
you should confirm your cuda version and cudnn version . Download the corresponding version。

**Comment by liu-zg15** [comment]
> you should confirm your cuda version and cudnn version . Download the corresponding version。

Sorry for late reply. 
I confirmed my CUDA version which is 10.1. The cudnn version is 7.6.1.
I guess I used the correct version. But the error still happens.

**Comment by liu-zg15** [comment]
> Hi, can you try download this wheel and then install?

Yes, I tried to download the wheel by firefox. But it also also failed.
/home/gone/Pictures/Screenshot from 2020-01-21 13-49-55.png
Is the error caused by network connections? (I am in China)
Can I visit the server from mainland?

**Comment by xchani** [comment]
It seems to be caused by poor network connection. Sure you can access this link from mainland. Could you please try ```wget -c WHEEL_LINK``` ? If still doesn't work, I can provide you another temporary accessible link.

**Comment by liu-zg15** [comment]
> It seems to be caused by poor network connection. Sure you can access this link from mainland. Could you please try `wget -c WHEEL_LINK` ? If still doesn't work, I can provide you another temporary accessible link.

Yes, I also tried the wget and it still doesn't work. 
Very appreciate for your help.

**Comment by xchani** [comment]
How about this one? https://share.cxhan.com/mxnet_cu101-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl

**Comment by liu-zg15** [comment]
> How about this one? https://share.cxhan.com/mxnet_cu101-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl

This link works！
Thank you so much for your help!

**Comment by Yobivas** [comment]
> How about this one? https://share.cxhan.com/mxnet_cu101-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl


I need this file too and the link is dead, could you please create another?
thanks!
