### ISSUE TITLE
How can I choose the best result detection_train.py?

### ISSUE THREAD

**Issue by vhnamgau** [TuSimple/simpledet#297]
After run python3 detection_train.py --config config/tridentnet_r50v1c4_c5_1x.py, 

We will have corresponding result in /experiments/tridentnet_r50v1c4_c5_1x
Ex: checkpoint-0001.params, checkpoint-0002.params, ...checkpoint-0006.params
Which is the best result in these file?

**Comment by RogerChern** [comment]
You can not choose the best result on the validation set if you are going
to report it. By default, all results are reported on the last checkpoint.
