### ISSUE TITLE
Why Why is the effective range set to these 3 ranges?

### ISSUE THREAD

**Issue by YilanWang** [TuSimple/simpledet#299]
First of all, I wish all developers a Happy New Year! Hope everyone can take care of yourself in this epidemic～
In tridentnet paper, the valid ranges are set to [0,90],[30,160],[90,∞]. What is the law of this setting? It seem that it has a little relationship of the scale seeting of coco , i.e., 30,90 or bigger.
Many thanks for your reply!

**Comment by RogerChern** [comment]
Scale awareness does not affect the final results much. The general
rationale is that we do not want the small branch to process large objects
and the same for the large branch.
