### ISSUE TITLE
TridentNet 速度问题

### ISSUE THREAD

**Issue by ou525** [TuSimple/simpledet#3]
Thanks to open source, how about the speed of TridentNet, how is it compared with yolo?

**Comment by RogerChern** [comment]
Tridentnet is a backbone, yolo is a detector.  You can apply trident block to yolo to get the best of both worlds.

**Comment by winstywang** [comment]
BTW, please use English in the issues, since there may be other researchers that don't speak Chinese are also interested in your issue.

**Comment by ou525** [comment]
Okay, I understand now, thanks.
