### ISSUE TITLE
in class RpnParam:  num_reg_class = 81  why?

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#302]
在cascade_r101v1_fpn_1x.py中
class RpnParam:
        class bbox_target:
            num_reg_class = 2  # RPN只判断proposal是目标还是背景。
但是在faster_r101v1_fpn_1x.py中
class RpnParam:
        class bbox_target:
            num_reg_class = 81  # 为什么是81呢？我觉得应该是2才行呀？为何是coco数据集的类别数+1？
![image](https://user-images.githubusercontent.com/20853353/73903261-7ff0ac80-48d3-11ea-99e1-e17c7f120f83.png)
thanks everyone!
happy new year!

**Comment by xchani** [comment]
Both is fine. The only difference is **class aware** and **class agnostic** proposal.

**Comment by huangzehao** [comment]
The parameters in RpnParam.bbox_target are used for generating regression bbox targets in rcnn stage. And there are class aware and class agnostic setting in rcnn stage.
