### ISSUE TITLE
stride = 16  or (4, 8, 16, 32, 64)  ? and why?

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#306]
### 在cascade_r101v1_fpn_1x.py中的
class RpnParam:
     class anchor_generate:
            scale = (8,)
            ratio = (0.5, 1.0, 2.0)
            [stride = (4, 8, 16, 32, 64) # 此处为(4, 8, 16, 32, 64)](url)
            image_anchor = 256
            max_side = 1400         
### 但是在tridentnet_r101v1c4_c5_1x.py中的
class RpnParam:
     class anchor_generate:
            scale = (2, 4, 8, 16, 32)
            ratio = (0.5, 1.0, 2.0)
            [stride = 16  # 此处为16 ](url)
            image_anchor = 256
为什么有这种区别呢？为什么在tridentnet中stride 不能等于 (4, 8, 16, 32, 64)呢？
这个stride是什么作用呢？
thanks everyone!
happy 2020!

**Comment by huangzehao** [comment]
In FPN, we generate anchors on multiple feature maps which have different strides.
In tridentnet, we only generate anchors on a single feature map whose stride is 16.

**Comment by dongzhenguo2016** [comment]
> In FPN, we generate anchors on multiple feature maps which have different strides.
> In tridentnet, we only generate anchors on a single feature map whose stride is 16.
thanks very much!
