### ISSUE TITLE
r101v1c4_c5_512roi_2x   is different from     r101v2c4_c5_256roi_1x   ?

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#307]
[在config目录下面](url)
### faster_r101v1c4_c5_512roi_2x.py与faster_r101v2c4_c5_256roi_1x.py
我想问一下r101指的是101层的resnet。  我在网上也没找到合适的解释，-_-
1. 但是r101v1与r101v2有什么不同呢？
2. c4_c5指的是什么意思呢？
3. 512roi与256roi为何不同呢？
4. 2x与1x分别又指的什么意思呢？
thanks everyone!
happy 2020!

**Comment by xchani** [comment]
1. ResNet has 2 versions: [v1](https://arxiv.org/abs/1512.03385) and [v2](https://arxiv.org/abs/1603.05027). The second one fixes identity problem in v1.
2. **c4_c5** means using features from **c4** in ResNet for roi pooling / align, and **c5** for R-CNN.
3. The only difference is number of Region-of-Interest (i.e. proposal).
4. Default training parameter is 6 epochs, and we denote it as **1x**, so **2x** indicates 12 epochs.
