### ISSUE TITLE
Is it really necessary to write 1x and 2x as two separate .py files?

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#309]
### 在config目录下面每个以_1x.py结尾的文件和对应的以_2x.py结尾的文件的唯一的区别就在于：
（In the config directory, the only difference between each file ending in _1x.py and the corresponding file ending in _2x.py is that：）
在config目录下面每个以_1x.py结尾的文件，
    class OptimizeParam:
        class schedule:
            begin_epoch = 0
            end_epoch = 12
            [lr_iter = [60000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image),
                       80000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)]](url)

在config目录下面每个以_2x.py结尾的文件，
    class OptimizeParam:
        class schedule:
            begin_epoch = 0
            end_epoch = 12
            [lr_iter = [120000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image),
                       160000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)]](url)
区别就在于lr_iter不同而已，所以我感觉单独分成两个.py文件有点冗余。

**所以，我感觉完全可以写成一个.py，然后把lr_iter当作参数传进去**

**Comment by RogerChern** [comment]
The config system is designed to be fully reproducible and should record as
much information as possible.
