### ISSUE TITLE
parameter setting: schedule, warmup

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#31]
For the scheduler setting, 
what is the meaning of '16' in the 
r_iter = [60000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image),
           80000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)]

why it is 16?  thanks

class OptimizeParam:
        class optimizer:
            type = "sgd"
            lr = 0.01 / 8 * len(KvstoreParam.gpus) * KvstoreParam.batch_image
            momentum = 0.9
            wd = 0.0001
            clip_gradient = 35

        class schedule:
            begin_epoch = 0
            end_epoch = 6
            lr_iter = [60000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image),
                       80000 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)]

        class warmup:
            type = "gradual"
            lr = 0.0
            iter = 750 * 16 // (len(KvstoreParam.gpus) * KvstoreParam.batch_image)

**Comment by xchani** [comment]
16 refers to the total number of images across gpus, i.e. ```batch_image``` x ```len(gpus)```
