### ISSUE TITLE
proposal_wo_gt is true or fasle ?

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#310]
In cascade_r101v2_c5_red_1x.py：
 class RpnParam:
        class subsample_proposal:
            proposal_wo_gt = **False**

but in tridentnet_r101v2c4_c5_1x.py:
 class RpnParam:
        class subsample_proposal:
            proposal_wo_gt = **True**

In the [fully_annotated_config.py](url) I see  that the comment for proposal_wo_gt is to add gt to the proposals 
1. why is different?
2. Why is proposal_wo_gt **false** in cascade_r101v2_c5_red_1x.py, but proposal_wo_gt  **true** in tridentnet_r101v2c4_c5_1x.py
Thanks very much!
I wish you a happy work and life！

**Comment by xchani** [comment]
To align with the official implementation of Cascade R-CNN, **proposal_wo_gt** is set to False. This won't affect the performance much.
