### ISSUE TITLE
建个QQ群交流吧

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#317]
商汤推出的mmdetection，活跃度很高。人家的开发人员还建了个QQ群，方便大家交流。在此强烈建议图森的开发维护人员建个QQ群或者微信群，方便大家交流，谢谢采纳！

**Comment by Miracle-hpf** [comment]
> 商汤推出的mmdetection，活跃度很高。人家的开发人员还建了个QQ群，方便大家交流。在此强烈建议图森的开发维护人员建个QQ群或者微信群，方便大家交流，谢谢采纳！

复议！

**Comment by zhangxue123** [comment]
我建了一个QQ群，群名simpledet，群号817529675，大家可以进来交流
