### ISSUE TITLE
When expand anchor ratio from 0.5, 1.0, 2.0 to 0.5, 0.75, 1.0, 1.5, 2.0, the RCNN loss becomes 5.1 or so

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#32]
When expanding anchor ratio, the rcnn loss is becoming bigger, can you help me how to reduce it? Any advice will be appreciated, thanks

**Comment by RogerChern** [comment]
Could you please provide your customized config file in pastebin so that we will have more info about your problem.

**Comment by DayChan** [comment]
I tried to expand my anchors as following:
```python
scale = (3, 5, 7, 9, 11, 13)
ratio = (0.5, 0.667, 1, 1.5, 2)
```
But it seems doesn't have impact on loss, the loss decreases as normal.
Can you post your config file or try to figure out whether the data input is right?
