### ISSUE TITLE
Adding a regression head

### ISSUE THREAD

**Issue by DecentMakeover** [TuSimple/simpledet#323]
Thanks for sharing your work.

In Faster Rcnn , Along with the classification head and a regression head i would like to add another regression head, how could i go about doing that ,thanks.

**Comment by zehuichen123** [comment]
maybe you can refer to this :)
https://github.com/TuSimple/simpledet/blob/8da8efe2c2d07e428a81e0b69909b661dfa5bce6/models/msrcnn/builder.py#L65

**Comment by DecentMakeover** [comment]
Thanks let me check this
