### ISSUE TITLE
simpledet真的是一个很坑的框架

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#328]
simpledet真的是一个很坑的框架
非常难用，bug很多
看的很恶心

**Comment by dongzhenguo2016** [comment]
太晦涩难懂了

**Comment by zhayanli** [comment]
我训练的结果不对，正问呢。

**Comment by kbyran** [comment]
Not agree. The code is well-organised and can also be modified for re-id, attribute and pose. See [here](https://github.com/kbyran/POINet).

**Comment by zehuichen123** [comment]
Life is hard, get used to it :)
