### ISSUE TITLE
Pretrained Models offline

### ISSUE THREAD

**Issue by Z0org** [TuSimple/simpledet#331]
I tried to download some of the pretrained models from the MODEL_ZOO.md but it seems all of them are offline.

**Comment by RogerChern** [comment]
Sorry for the inconvenience, fixed.

**Comment by dongjuns** [comment]
Hey, I just prepared it on my google drive for emergency people.
<https://drive.google.com/drive/folders/1XM20eVMvSIGyCwn_hKCDcWt3zalrTYl1>
