### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by abigeer** [TuSimple/simpledet#34]
sudo nvidia-docker run -it -v $HOST-SIMPLEDET-DIR:$CONTAINER-WORKDIR rogerchen/simpledet /usr/bin/zsh
[sudo] password for koufeitian: 
docker: Error response from daemon: invalid volume specification: '-SIMPLEDET-DIR:-WORKDIR': invalid mount config for type "volume": invalid mount path: '-WORKDIR' mount path must be absolute.
See 'docker run --help'.

**Comment by xchani** [comment]
Please refer to [this](https://github.com/TuSimple/simpledet/issues/15#issuecomment-462707368).

**Comment by dongjuns** [comment]
Hey, refer to <https://dongjuns.github.io/simpledet/object/detection/simpledet-tutorial/>
I explained some docker information for simpledet users.
