### ISSUE TITLE
Name or service not known.

### ISSUE THREAD

**Issue by zhangxue123** [TuSimple/simpledet#348]
004:~/Public/singularity-2.6.1$ wget https://1dv.alarge.space/simpledet.img

--2020-12-03 11:41:28--  https://1dv.alarge.space/simpledet.img
Resolving 1dv.alarge.space (1dv.alarge.space)... failed: Name or service not known.
wget: unable to resolve host address ‘1dv.alarge.space’

I want to know about the new mirror website， Thank you very much！

**Comment by huangzehao** [comment]
Hi, please use `wget https://1dv.aflat.top/simpledet.img.`

**Comment by zhangxue123** [comment]
> https://1dv.aflat.top/simpledet.img

mdl@imdl-004:~/Public/simpledet$ wget https://1dv.aflat.top/simpledet.img
--2020-12-03 17:00:58--  https://1dv.aflat.top/simpledet.img
Resolving 1dv.aflat.top (1dv.aflat.top)... 47.240.59.72
Connecting to 1dv.aflat.top (1dv.aflat.top)|47.240.59.72|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-03 17:00:58 ERROR 404: Not Found.

**Comment by huangzehao** [comment]
@zhangxue123 Sorry, use `https://oss.aflat.top/simpledet.img`.

**Comment by zhangxue123** [comment]
> @zhangxue123 Sorry, use `https://oss.aflat.top/simpledet.img`.

@huangzehao It don't import mxnet in https://oss.aflat.top/simpledet.img,   I find python3 version is 3.5 in img, and mxnet in python3.6, I want to know how to solve！

**Comment by zhangxue123** [comment]
> @zhangxue123 Sorry, use `https://oss.aflat.top/simpledet.img`.
@huangzehao 
I install python3.6.8 in img, defult path in /usr/local/lib/python3.6, I do ln -s /root/.pyenv/versions/3.6.8/lib/python3.6/ /usr/local/lib/python3.6/, still cannot import mxnet.
