### ISSUE TITLE
There is no method "mx.sym.contrib.BroadcastScale" in mxnet

### ISSUE THREAD

**Issue by rwecho** [TuSimple/simpledet#350]
Hi, I bought Nvidia 3070 to run simpledet. But mxnet can not run with cuda 10.1 on 3070. 
To compile mxnet, I try to find the source corresponding to simpledet. 
I can not found the gen_contrib.py in the history of mxnet 1.6.
So is there anyone working with the new Graphics card?  Thanks.

**Comment by rwecho** [comment]
compare [apache-mxnet-package](https://repo.mxnet.io/dist/python/cu101/mxnet_cu101-1.6.0b20191214-py2.py3-none-manylinux1_x86_64.whl) with [simpledet-package](https://1dv.aflat.top/mxnet_cu101-1.6.0b20191214-py2.py3-none-manylinux1_x86_64.whl) 

There are some file not exists in apache
* gen__internal.py
* gen_contrib.py
* gen_xxx.py

I'm new here, did not how gen_xx.py inject to mxnet package when compiling for cuda 11.
Help, please.

**Comment by huangzehao** [comment]
Similar to https://github.com/TuSimple/simpledet/issues/351.
Is your cuda version 11.1? We will build an image for it.

**Comment by rwecho** [comment]
yes, I'm planning to run on cuda 11.1.
thanks.

**Comment by huangzehao** [comment]
@rwecho 
We provide a dockerfile in https://github.com/TuSimple/simpledet/tree/master/docker.
I test the docker on gpu 3090 with cuda11.1 and cudnn8. It works.

**Comment by rwecho** [comment]
@huangzehao thanks, I'll test on my Nvidia 3070, and commit the result here.

**Comment by rwecho** [comment]
@huangzehao 
I test the dockerfile and failed. it warning as below:

``` bash
nvcc fatal   : Unsupported gpu architecture 'compute_80'
nvcc fatal   : Unsupported gpu architecture 'compute_86'
```

**Comment by huangzehao** [comment]
I guess your cuda version is 11.0 instead of 11.1?
You can try update cuda from 11.0 to 11.1 or remove 
`-gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86` from 
` echo 'CUDA_ARCH = -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86' >> ./config.mk && \
` in dockerfile

**Comment by rwecho** [comment]
The Cuda version in the dockerfile specified as 10.2?

**Comment by huangzehao** [comment]
https://github.com/TuSimple/simpledet/tree/master/docker#build

**Comment by rwecho** [comment]
> https://github.com/TuSimple/simpledet/tree/master/docker#build

Ignore the build args, I'll try it again. thanks.
