### ISSUE TITLE
Support for newer version of MXNet, CUDA 11, and 30-series NVIDIA GPU

### ISSUE THREAD

**Issue by kzhang0718** [TuSimple/simpledet#351]
Hi,

Just wondering if there's any existing plan for supporting latest version of MXNet? The MXNet version used by simpledet does not support 30-series NVIDIA GPU, which requires CUDA 11. Yet I could not successfully compile this version of MXNet with CUDA 11.

Thanks.

**Comment by RogerChern** [comment]
I will see to it during the new year holidays.

**Comment by huangzehao** [comment]
@kzhang0718  We provide a dockerfile now.
Please refer https://github.com/TuSimple/simpledet/issues/350.

**Comment by kzhang0718** [comment]
Thanks! Will try it out.
