### ISSUE TITLE
The links for pretrained models are dead

### ISSUE THREAD

**Issue by waltsky** [TuSimple/simpledet#358]
**Describe the bug**

**Screenshots or stack traces**
If applicable, add screenshots or stack traces to help explain your problem.

**Which config are you using**

**Which dataset are you using **

**Hardware info**
CPU, GPU, Storage(Disk or NFS)

**Software info**
driver, CUDA, cuDNN versions
OS verison

**How did you set up your MXNet for SimpleDet**

**Additional context**

**Comment by RogerChern** [comment]
All dead links are fixed
