### ISSUE TITLE
The performance and speed for training Tridentnet Faster-RCNN with fp16

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#36]
I think I didn't find the records of Tridentnet Faster-RCNN with fp16. Can you provide it? Do the performances of Tridentnet Faster-RCNN with fp16 and without fp16 have a large difference? Thanks

**Comment by RogerChern** [comment]
FP16 generally have no impact on performance. At now, not every model has its FP16 companion. The final model in our paper is trained with fp16 and you can find it on the [trident page](https://github.com/TuSimple/simpledet/tree/master/models/tridentnet).

**Comment by hdjsjyl** [comment]
@RogerChern   Got it. Thanks for your reply. And for plain faster rcnn, when I use my own faster rcnn, and faster rcnn implemented by you to fit my dataset with the same parameter setting, the results are different and have a big difference. Do you think I should set different parameters? Do you have any advice about that? Thanks
