### ISSUE TITLE
All URLs for prebuilt MXNet are dead

### ISSUE THREAD

**Issue by csmailis** [TuSimple/simpledet#360]
All URLs for downloading the prebuilt MXNet versions that your project uses provided in the https://github.com/TuSimple/simpledet/blob/master/doc/INSTALL.md document are dead. 
The same applies to the URLs of MXNet in the ReadMe.md

Similarly, the links of the docker and singularity images are dead.
In general, it seems that all content your project had on the https://1dv.aflat.top/ server is not accessible anymore.
I am kindly asking if it would be possible to reupload the contents of these URLs and provide updated links?

**Comment by RogerChern** [comment]
All dead links are fixed.

**Comment by csmailis** [comment]
The links are dead again, just tested them.

**Comment by RogerChern** [comment]
Please stay tuned. I am checking right now.

**Comment by RogerChern** [comment]
I think at least https://1dv.aflat.top/mxnet_cu101-1.6.0b20191214-py2.py3-none-manylinux1_x86_64.whl should be accessable now.

I'm flushing caches for other files.

**Comment by csmailis** [comment]
Yes, at least the MXnet related links do work now. Thanks!

**Comment by RogerChern** [comment]
The domain name used here seems expired. I will fix it ASAP.

csmailis ***@***.***>于2022年3月16日 周三上午1:56写道：
