### ISSUE TITLE
The difference of performance of my own faster rcnn and faster rcnn in this project

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#37]
For plain faster rcnn, when I use my own faster rcnn, and faster rcnn implemented in this project to fit my dataset with the same parameter setting and the same network structure, the results are different and have a large difference. Do you think I should set different parameters? Do you have any advice about that? Thanks

**Comment by winstywang** [comment]
The devils are in the details.

**Comment by hdjsjyl** [comment]
@winstywang  thanks for your reply. I am checking the difference of the code to understand the different performances.
