### ISSUE TITLE
where is the package ‘mxnext’？

### ISSUE THREAD

**Issue by xiangliu886** [TuSimple/simpledet#4]
import mxnet as mx
import mxnext as X
where is the package ‘mxnext’？

**Comment by winstywang** [comment]
Please refer to the Installation section carefully.

**Comment by RogerChern** [comment]
As already specified in Setup, you can get mxnext from https://github.com/RogerChern/mxnext

**Comment by xiangliu886** [comment]
Thank you！

**Comment by wait1988** [comment]
@RogerChern what cause the problem "ImportError: No module named 'config.detection_config'"?
