### ISSUE TITLE
Confusion on performance. Different numbers from my rerun, model_zoo and original paper. 

### ISSUE THREAD

**Issue by huangh12** [TuSimple/simpledet#40]
@RogerChern hi, thanks for your great work.
I run the code recently. 
Without any modifications of the config file(except that gpu is reduced from 8 to 4), my results are:
Faster | R50v2-C4 | C5-256ROI | 33.9 (config file: faster_r50v2c4_c5_256roi_1x.py)
Faster | R101v2-C4 | C5-256ROI | 38.9  (config file: faster_r101v2c4_c5_256roi_1x.py)
These are quite different from the accuracy you gave on [MODEL_ZOO.md](https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md)(see below). 
![default](https://user-images.githubusercontent.com/18748036/53863368-0007f580-4025-11e9-809a-e17266110153.png)
![default](https://user-images.githubusercontent.com/18748036/53863387-0dbd7b00-4025-11e9-8f70-9e3c01b5d790.png)

What's more, it's also different from the numbers in your trident paper (I guess they are 33.2 and 37.9 respectively).
![default](https://user-images.githubusercontent.com/18748036/53863512-5ecd6f00-4025-11e9-89d6-749c30e48eeb.png)

Could you please give some clarification? Thank you.

**Comment by RogerChern** [comment]
1. MODEL_ZOO.md contains results from a very early verison of SimpleDet, and we will upgrade the results soon.
2. TridentNet is not originally trained in SimpleDet and we migrate existing models to SimpleDet without re-training. We can obtain a slight higher result (+0.8-0.9 mAP) for TridentNets on current codebase.

**Comment by bailvwangzi** [comment]
"We can obtain a slight higher result (+0.8-0.9 mAP) for TridentNets on current codebase."
why can get higher result without re-training?Can you explain in detail?
