### ISSUE TITLE
Infer_shape error when fine tune on new dataset

### ISSUE THREAD

**Issue by mikelam14** [TuSimple/simpledet#41]
Hi,

I am using the pretrained faster_r50v1_fpn_1x weights and I want to fine tune on my dataset which has 1+2 classes. When I change the config from 1+80 to 1+2, the code runs into "infer_shape error". How do I specify to change the last layer or how should I change the config instead? Thank you.

**Comment by RogerChern** [comment]
Please remove the weight of rcnn classification head from the pretrain model.
