### ISSUE TITLE
Any suggestion about model ensemble for faster rcnn? 

### ISSUE THREAD

**Issue by BasisPoint** [TuSimple/simpledet#42]
I have trained several faster rcnn models with different backbones, then I want to ensemble these models for a better performance, but I am totally confused about how to do this, can you give me some suggestion or reference for this? Thank you anyway.

**Comment by RogerChern** [comment]
In `detection_test.py`, we aggregate all `output_record` with the same `im_id` in `all_output`, as shown in [here](https://github.com/TuSimple/simpledet/blob/master/detection_test.py#L128-L150). If you want to do ensemble testing, you should save the `all_output` as pickle for all models you tested. And concate them as a single `all_output` for downstream evaluation.
