### ISSUE TITLE
import mxnext error

### ISSUE THREAD

**Issue by lucheng07082221** [TuSimple/simpledet#43]
>>> import mxnext
[Warning] Your mxnet does not support ProposalTarget
[Warning] Your mxnet does not support DecodeBBox
[Warning] Your mxnet does not support BBoxNorm
[Warning] Your mxnet does not support FocalLoss

but in my folder:/home/lc/work/simpledet/operator_cxx/contrib has focal_loss.cu focal_loss.cc focal_loss.o ...

**Comment by RogerChern** [comment]
Please consider use pre-built docker or singularity image for setting up if you are not very familiar with building MXNet from scratch.

**Comment by huo123lijuan** [comment]
I meet the same problem,I don't familiar with docker and singularity,and don't know how to use these tools,can you give me some advice?

**Comment by dongjuns** [comment]
I made some tutorial for simpledet users who is not familiar with docker,
maybe you can find some information and troubleshooting also in there.

<https://dongjuns.github.io/simpledet/object/detection/simpledet-tutorial/>
