### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by yuyijie1995** [TuSimple/simpledet#46]
d/src/kvstore/kvstore.o
In file included from src/kvstore/kvstore.cc:35:0:
src/kvstore/./kvstore_nccl.h:30:18: fatal error: nccl.h: 没有那个文件或目录
compilation terminated.
Makefile:451: recipe for target 'build/src/kvstore/kvstore.o' failed
make: *** [build/src/kvstore/kvstore.o] Error 1

when i try to make it ,this error happened

**Comment by RogerChern** [comment]
Please refer to #43

**Comment by qusongyun** [comment]
> d/src/kvstore/kvstore.o
> In file included from src/kvstore/kvstore.cc:35:0:
> src/kvstore/./kvstore_nccl.h:30:18: fatal error: nccl.h: 没有那个文件或目录
> compilation terminated.
> Makefile:451: recipe for target 'build/src/kvstore/kvstore.o' failed
> make: *** [build/src/kvstore/kvstore.o] Error 1
> 
> when i try to make it ,this error happened

Hello, have you solved this problem? I meet the same, but i don not how to  use docker or singualr

**Comment by PumayHui** [comment]
The same error...
