### ISSUE TITLE
Confused about code implementation kept_rois[i].push_back(gt_tmp) in proposal_target_v2-inl.h

### ISSUE THREAD

**Issue by v-qjqs** [TuSimple/simpledet#49]
I’m reading paper and code implementation of TridentNet. I’m confused about code kept_rois[i].push_back(gt_tmp); in proposal_target_v2-inl.h, Line 204.
I wonder whether gt_tmp should be appended to kept_rois[i] or not. I mean that vector kept_rois[i] keep value of proposal boxes (generated by RPN etc.) at current scale (valid range) i, and gt box may should not be added to this vector. Also, I wonder those invalid gt_boxes (at scale i) should be removed from kept_gtbboxes[i] or not. It seems that invalid gt_boxes (at scale i) don’t be removed from kept_gtbboxes[i] in code implementation.
So incorrect overlap value may be calculated when BBoxOverlap(all_rois, gt_boxes, IOUs) invoked? As tensor ‘all_rois’ may has gt boxes, and tensor ‘gt_boxes’ may has gt boxes which are invalid at current scale (valid range) i.
I wonder it’s an issue or my misunderstanding. Thanks very much.

**Comment by RogerChern** [comment]
Appending ground truth bounding box to proposals during training is a standard method. For trident, we only append ground truth bboxes which are within the valid range of each branch.
