### ISSUE TITLE
Training log sharing

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#5]
First, thank you for sharing these excellent works. Can you share some logs when you trained the model for faster rcnn, mask rcnn or tridentnet work? Because I want to use our own dataset to train the model. So the log information can help me to tune the parameters. Thanks

**Comment by RogerChern** [comment]
Logs are included in zip files in MODEL_ZOO

**Comment by hdjsjyl** [comment]
@RogerChern Sorry, MODEL_ZOO is a folder in this project? I didn't find it. Can you give me a relative path? Thanks

**Comment by RuiminChen** [comment]
> @RogerChern Sorry, MODEL_ZOO is a folder in this project? I didn't find it. Can you give me a relative path? Thanks
https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md
Honestly, you should pay more attention rather than just asking.

**Comment by RuiminChen** [comment]
> @RogerChern Sorry, MODEL_ZOO is a folder in this project? I didn't find it. Can you give me a relative path? Thanks
https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md
Honestly, you should pay more attention rather than just keep asking.

**Comment by hdjsjyl** [comment]
@RuiminChen , Sorry about asking a simple question. I saw MODEL_ZOO.md file. The training log information I asked means the variance of loss, speed, accuracy and false positives. Thanks

**Comment by RogerChern** [comment]
Sorry for the confusion, the last column of the first Table in MODEL_ZOO.md provides links to pretrained models and logs.
