### ISSUE TITLE
Sometimes, RcnnL1 is nan for the first 100 epoch or so, after that the loss is normal. Why it happened? 

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#50]
Sometimes, RcnnL1 is nan for the first 100 epoch, after that the loss is normal. Why it happened?

**Comment by roadcode** [comment]
similarity problem, the log is like this:
03-21 20:21:43 Epoch[0] Batch [3300]	Speed: 16.26 samples/sec	Train-RpnAcc=0.918204,	RpnL1=nan,	RcnnAcc=0.940387,	RcnnL1=nan,	
and after save checkpoint
the log is like:
03-22 00:53:13 Epoch[1] Batch [20]	Speed: 16.12 samples/sec	Train-RpnAcc=0.887285,	RpnL1=0.852888,	RcnnAcc=0.988638,	RcnnL1=nan,	

what will cause RcnnL1 loss to be nan?

**Comment by RogerChern** [comment]
Could you please add more details of your setting. 100 epochs for detection training does not make much sense to me.

**Comment by RogerChern** [comment]
Closed due to inactivity.

**Comment by ztyxd** [comment]
i have the same problem, 
when i  use  tridentnet_r101v2c4_c5_addminival_2x with my own dataset. 

The RPNL1LOSS and rcnnl1loss is normal  at first,  but after about 3000 iterarion the rcnnL1loss will be nan  and  RPNl1loss will be a  large number.

I use the code with only one GPU ,
and i donnot change other config unless the gpus in KVstoreParam
