### ISSUE TITLE
how to ensure all the detail of mxnet is completely installed？

### ISSUE THREAD

**Issue by handsomefengfeng** [TuSimple/simpledet#51]
After finishing the setup，I began to train the model. But the error arose.
How can i address this?
The log follows.

Traceback (most recent call last):
  File "detection_train.py", line 12, in <module>
    from core.detection_module import DetModule
  File "/home/yyf/simpledet/core/detection_module.py", line 29, in <module>
    from mxnet import metric
ImportError: cannot import name 'metric'

**Comment by RogerChern** [comment]
This looks like a misconfiguration of MXNet itself. Maybe [MXNet](https://github.com/apache/incubator-mxnet) guys could you out.
