### ISSUE TITLE
Submodule init 

### ISSUE THREAD

**Issue by handsomefengfeng** [TuSimple/simpledet#52]
The response of command" git submodule init" is below:

yyf@tower-pc:~/simpledet-master/mxnet$ git submodule init
子模组 '3rdparty/cub' (https://github.com/dmlc/cub) 未对路径 '3rdparty/cub' 注册
子模组 '3rdparty/dlpack' (https://github.com/dmlc/dlpack) 未对路径 '3rdparty/dlpack' 注册
子模组 '3rdparty/dmlc-core' (https://github.com/dmlc/dmlc-core.git) 未对路径 '3rdparty/dmlc-core' 注册
子模组 '3rdparty/googletest' (https://github.com/google/googletest.git) 未对路径 '3rdparty/googletest' 注册
子模组 '3rdparty/mkldnn' (https://github.com/intel/mkl-dnn.git) 未对路径 '3rdparty/mkldnn' 注册
子模组 '3rdparty/mshadow' (https://github.com/dmlc/mshadow.git) 未对路径 '3rdparty/mshadow' 注册
子模组 '3rdparty/onnx-tensorrt' (https://github.com/onnx/onnx-tensorrt.git) 未对路径 '3rdparty/onnx-tensorrt' 注册
子模组 '3rdparty/openmp' (https://github.com/llvm-mirror/openmp) 未对路径 '3rdparty/openmp' 注册
子模组 '3rdparty/ps-lite' (https://github.com/dmlc/ps-lite) 未对路径 '3rdparty/ps-lite' 注册
子模组 '3rdparty/tvm' (https://github.com/dmlc/tvm) 未对路径 '3rdparty/tvm' 注册

Is it a wrong behavior?

And then, after finishing the "cp" command, I'm wonderring what's going wrong.
Just a couple files are missing.
And i get the mxnet as the command in your github.How can i solve it?
Thanks.

**Comment by RogerChern** [comment]
Please refer to #53
