### ISSUE TITLE
install from strach

### ISSUE THREAD

**Issue by ztyxd** [TuSimple/simpledet#53]
when i install from strach i have got the problem:
I use anaconda 3  and do install cuda9.2 ,cudnn 7.3.1 . 
   when i  input make -j  in my anaconda env:
     it  have something wrong:
  In file included from /home/zty/Documents/simpledet/mxnet/3rdparty/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:32,
                 from include/mxnet/operator_util.h:43,
                 from src/operator/contrib/./quadratic_op-inl.h:29,
                 from src/operator/contrib/quadratic_op.cc:24:
/home/zty/Documents/simpledet/mxnet/3rdparty/mshadow/mshadow/./base.h:179:21: fatal error: cudnn.h: No such file or directory

**Comment by RogerChern** [comment]
More related to MXNet than SimpleDet. Please refer to #51
