### ISSUE TITLE
About the train time

### ISSUE THREAD

**Issue by qusongyun** [TuSimple/simpledet#56]
Hello, I want to know how many GPUS have you used and how long have you trained this network on coco dataset?

**Comment by RogerChern** [comment]
For small detectors like r50 + c5 head + 256 roi, the 1x scheme takes 12 hours with 8X 1080Ti.

**Comment by 1179021477** [comment]
Is there any methods to make the training faster? Like using multi-thread?

**Comment by 1179021477** [comment]
@RogerChern I train tridentNet with resnet50 on 4 GPU (a machine with 8 GPU), and I need 2 days. Especially, when others use another GPU in my machines, the speed of my models is slower. Is there any way to make training faster?
