### ISSUE TITLE
when i  use the tridentnet, the rpnl1 loss will be a large number and the rcnnl1loss will be nan,how can i solve this problem?

### ISSUE THREAD

**Issue by ztyxd** [TuSimple/simpledet#57]
when i use tridentnet_r101v2c4_c5_addminival_2x with my own dataset.

The RPNL1LOSS and rcnnl1loss is normal at first, but after about 3000 iterarion the rcnnL1loss will be nan and RPNl1loss will be a large number.

I use the code with only one GPU ,
and i donnot change other config unless the gpus in KVstoreParam

**Comment by RogerChern** [comment]
Without any details about your own dataset, the best guess should be that the learning rate is too large. Try to decease your lr.

**Comment by ztyxd** [comment]
thanks a lot.
