### ISSUE TITLE
/utils/generate_roidb.py#L30   

### ISSUE THREAD

**Issue by liugl7** [TuSimple/simpledet#58]
[https://github.com/TuSimple/simpledet/blob/master/utils/generate_roidb.py#L30](https://github.com/TuSimple/simpledet/blob/fc4437fd414057f3a1e845dcb40ab753b3c3ed6a/utils/generate_roidb.py#L30)

should be modified as

`annotation_path = "data/%s/annotations/%s_%s.json" % (dataset_name, annotation_type, dataset_split_mapping[dataset_split])`

??

**Comment by RogerChern** [comment]
No, it shall not.

**Comment by liugl7** [comment]
When you enter the following command, 
`python3 utils/generate_roidb.py --dataset coco --dataset-split valminusminival2014`

it will report an error.
`FileNotFoundError: [Errno 2] No such file or directory: '/home/lgl/datasets/coco/annotations/instances_valminusminival2014.json'`

In   the `~/datasets/coco/annotations/isntances_*****.json` ， there  are only 
`instances_train2014.json   instances_train2017.json   instances_val2014.json     instances_val2017.json  `
