### ISSUE TITLE
ModuleNotFoundError: No module named 'config.detection_config'

### ISSUE THREAD

**Issue by huo123lijuan** [TuSimple/simpledet#60]

**Comment by xchani** [comment]
There is no such config named `detection_config.py`. To train `TridentNet`, you could try to run `python3 detection_train.py --config config/tridentnet_r50v2c4_c5_1x.py`.

**Comment by 2110317008** [comment]
root@dca9a5a154d6:/home/simpledet# CUDA_VISIBLE_DEVICES=0 python3 detection_train.py --config config/tridentnet_r50v2c4_c5_1x.py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[Warning] Your mxnet does not support ProposalTarget
[Warning] Your mxnet does not support BBoxNorm
[Warning] Your mxnet does not support FocalLoss
Traceback (most recent call last):
  File "detection_train.py", line 276, in <module>
    train_net(parse_args())
  File "detection_train.py", line 21, in train_net
    transform, data_name, label_name, metric_list = config.get_config(is_train=True)
  File "/home/simpledet/config/tridentnet_r50v2c4_c5_1x.py", line 133, in get_config
    num_branch=Trident.num_branch, scaleaware=Trident.train_scaleaware)
  File "/home/simpledet/models/tridentnet/builder.py", line 86, in get_train_symbol
    proposal, bbox_cls, bbox_target, bbox_weight = rpn_head.get_sampled_proposal_with_filter(rpn_feat, gt_bbox, im_info, valid_ranges)
  File "/home/simpledet/models/tridentnet/builder.py", line 279, in get_sampled_proposal_with_filter
    (proposal, proposal_score) = self.get_all_proposal_with_filter(conv_feat, im_info, valid_ranges)
  File "/home/simpledet/models/tridentnet/builder.py", line 239, in get_all_proposal_with_filter
    proposal = mx.sym.contrib.Proposal_v2(
AttributeError: module 'mxnet.symbol.contrib' has no attribute 'Proposal_v2'
root@dca9a5a154d6:/home/simpledet#
when i run python3 detection_train.py --config config/tridentnet_r50v2c4_c5_1x.py ,i get this error.How to solve this problem？
