### ISSUE TITLE
Wrong batchsize in MODEL_ZOO for TridentNet-101

### ISSUE THREAD

**Issue by qusongyun** [TuSimple/simpledet#61]
Hello, in your MODLE.md. Model trident-101-c4 use 2images/gpu and 6.6G memory. But,in your config file, the <batch_image> is equal to 1, In my experiment（2 titanx/<batch_image>=1）, the memory being used that of each gpu is  up to 7.2G/12G. So, what's the reason?

**Comment by ztyxd** [comment]
I have the same problem, do you handle this problem now ?
thanks a lot

**Comment by xchani** [comment]
It seems to be a mistake in **MODEL_ZOO**, since batch size for TridentNet-101 is 1 both for training and testing.

**Comment by ztyxd** [comment]
OK, thanks

**Comment by xchani** [comment]
Fixed in latest commit.
