### ISSUE TITLE
ModuleNotFoundError: No module named 'mxnext'

### ISSUE THREAD

**Issue by huo123lijuan** [TuSimple/simpledet#62]

**Comment by xchani** [comment]
Try `pip3 list | grep mxnext` to confirm whether `mxnext` is well installed.

**Comment by huo123lijuan** [comment]
Thank you.
New problems arise. when I run 
        python3 detection_train.py --config config/tridentnet_r50v2c4_c5_1x.py
AttributeError: module 'mxnet.symbol.contrib' has no attribute 'Proposal_v2'

**Comment by xchani** [comment]
It indicates that the mxnet you use is not compiled with **custom operators** provided in SimpleDet. Please read [INSTALL](https://github.com/TuSimple/simpledet/blob/master/doc/INSTALL.md) more carefully.

**Comment by huo123lijuan** [comment]
When install mxnet ,run "make -j",ｉs there anything wrong with that?
Makefile:284: WARNING: Significant performance increases can be achieved by installing and enabling gperftools or jemalloc development packages
INFO: nvcc was not found on your path
INFO: Using /usr/local/cuda/bin/nvcc as nvcc path
Running CUDA_ARCH: -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=[sm_70,compute_70] --fatbin-options -compress-all
make CXX="g++" DEPS_PATH="/home/hlj/mxnet/deps" -C /home/hlj/mxnet/3rdparty/ps-lite ps
cd /home/hlj/mxnet/3rdparty/dmlc-core; make libdmlc.a USE_SSE=1 config=/home/hlj/mxnet/config.mk; cd /home/hlj/mxnet
make[1]: Entering directory '/home/hlj/mxnet/3rdparty/dmlc-core'
make[1]: 'libdmlc.a' is up to date.
make[1]: Leaving directory '/home/hlj/mxnet/3rdparty/dmlc-core'
make[1]: Entering directory '/home/hlj/mxnet/3rdparty/ps-lite'
make[1]: Nothing to be done for 'ps'.
make[1]: Leaving directory '/home/hlj/mxnet/3rdparty/ps-lite'
ar crv lib/libmxnet.a

**Comment by xchani** [comment]
Please refer to #51.

**Comment by feixiangdekaka** [comment]
> _No description provided._

 

python3 detection_test.py --config config/tridentnet_r50v2c4_c5_1x.py
Traceback (most recent call last):
  File "detection_test.py", line 3, in <module>
    from core.detection_module import DetModule
  File "/tmp/simpledet/core/detection_module.py", line 27, in <module>
    import mxnet
ImportError: No module named 'mxnet'
have  you solve  it?

**Comment by 2110317008** [comment]
> Thank you.
> New problems arise. when I run
> python3 detection_train.py --config config/tridentnet_r50v2c4_c5_1x.py
> AttributeError: module 'mxnet.symbol.contrib' has no attribute 'Proposal_v2'

I have the same problem. How did you solve it？
