### ISSUE TITLE
undefined symbol when import mxnet

### ISSUE THREAD

**Issue by lji72** [TuSimple/simpledet#63]
OSError: /home/liuji/experiments/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _Z9rleDecodePK3RLEPhm

when install mxnet using cuda 9.0, cudnn 7.0, ubuntu 16.04 from  Scratch。Could give some advice？

**Comment by xchani** [comment]
Please refer to #51.

**Comment by Baby47** [comment]
Ｈi, @lji72,i meet the same problem with you. Have you figure it out?

**Comment by xchani** [comment]
SimpleDet use COCO API to encode mask, whose **header files** should be put into the mxnet folder.
```Shell
mkdir -p src/coco_api
cp -r $COCOAPI_DIR/common src/coco_api/
```

**Comment by Baby47** [comment]
I have done this, but the same error happend. @xchani

**Comment by dreadlord1984** [comment]
https://github.com/apache/incubator-mxnet/issues/14471

**Comment by RogerChern** [comment]
@Baby47 Check the existence of `maskApi.cc` under `src/coco_api`.
