### ISSUE TITLE
terminate called without an active exception ,terminate called recursively

### ISSUE THREAD

**Issue by huo123lijuan** [TuSimple/simpledet#67]
mxnet.base.MXNetError: [07:32:30] src/ndarray/ndarray.cc:1749: Check failed: fi->Read(&header) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5b) [0x7fc4ab4a243b]
[bt] (1) /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7fc4ab4a2fa8]
[bt] (2) /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::NDArray::Load(dmlc::Stream*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)+0xa2) [0x7fc4adfb2ad2]
[bt] (3) /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(MXNDArrayLoad+0x277) [0x7fc4ae581227]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc4d7a51e40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fc4d7a518ab]
[bt] (6) /root/.pyenv/versions/3.6.8/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7fc4d7c65eef]
[bt] (7) /root/.pyenv/versions/3.6.8/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x8de9) [0x7fc4d7c5cde9]
[bt] (8) /root/.pyenv/versions/3.6.8/lib/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x8a) [0x7fc4d91f772a]
[bt] (9) /root/.pyenv/versions/3.6.8/lib/libpython3.6m.so.1.0(+0x160bd8) [0x7fc4d92e4bd8]
terminate called without an active exception
terminate called recursively

**Comment by anirudh2290** [comment]
which mxnet version ? can you provide repro steps.

**Comment by RogerChern** [comment]
This bug is generally triggered by trying to load checkpoint generated by a higher version MXNet in a lower version MXNet.
