### ISSUE TITLE
RpnL1 loss and RcnnL1 loss suddenly become biger

### ISSUE THREAD

**Issue by ACkuku** [TuSimple/simpledet#70]
![image](https://user-images.githubusercontent.com/16281985/55924042-d9983400-5c3a-11e9-80b3-68d18e759f8c.png)
training coco dataset, and I changed the `tridentnet_r101v2c4_c5_1x.py`, 
 only changed `gpus=[0, 1]`, and the `lr = 0.001 / 8 * len(KvstoreParam.gpus) * KvstoreParam.batch_image`.

**Comment by RogerChern** [comment]
Could you please rerun this experiment? Gradient corruption this late in training should be extremely rare.
