### ISSUE TITLE
Pascal VOC format data

### ISSUE THREAD

**Issue by qilicun** [TuSimple/simpledet#8]
Hi!
Really great job! Thank you!

I just wonder if you could provide pascal voc format data loader?  I think this is also very useful, thanks again.

**Comment by RogerChern** [comment]
It seems that the provider of coco dataset has already convert the VOC annotation to coco format. Please reffer to http://cocodataset.org/#external 
 and https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip for more info.
