### ISSUE TITLE
Where is the tridentnet of resnet-101-deformable code?

### ISSUE THREAD

**Issue by heiyuxiaokai** [TuSimple/simpledet#80]
Like the comparison in your paper.
![TIM图片20190425212742](https://user-images.githubusercontent.com/27018045/56739354-0737be00-67a1-11e9-953f-783cfbf0b46e.png)

**Comment by xchani** [comment]
refer to ```config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py```
