### ISSUE TITLE
Images without any annotation

### ISSUE THREAD

**Issue by arc144** [TuSimple/simpledet#82]
Hi, first of all, congratulations for this amazing library!

I intend to retrain a network from model zoo on a custom dataset and this dataset contains images without any ground-truth annotations (images without any classes, everything is background). 

Is the code adapted to receive images without any annotation? 

Another doubt, how can I load a model from model zoo and change the last layer to change the number of classes?

Thanks a lot

**Comment by RogerChern** [comment]
Sorry for the late reply. 
1. Image without gt is filtered to ease the implementation. But you can fake a ground truth bbox with (0, 0, 0, 0) for your purpose.
2. You can refer to `mxnet.model.load_checkpoint` for tailoring pretrained models
