### ISSUE TITLE
error when run trident network with coco dataset

### ISSUE THREAD

**Issue by runzeer** [TuSimple/simpledet#83]
Hi, recently when I run the trident network with coco dataset. The error occured. The log is as follows. Could you help me ?  

load pretrain_model/resnet-50-0000.params
05-04 16:16:09 total iter 351798
05-04 16:16:09 lr 0.005, lr_iters [240000, 320000]
05-04 16:16:09 warmup lr 0.0, warmup step 12000
05-04 16:16:28 Initialized bbox_cls_logit_bias as bias: 0.0
05-04 16:16:28 Initialized bbox_cls_logit_weight as ["normal", {"sigma": 0.01}]: 0.010004348
05-04 16:16:28 Initialized bbox_reg_delta_bias as bias: 0.0
05-04 16:16:28 Initialized bbox_reg_delta_weight as ["normal", {"sigma": 0.001}]: 0.0009957128
05-04 16:16:28 Initialized rpn_bbox_delta_bias as bias: 0.0
05-04 16:16:28 Initialized rpn_bbox_delta_weight as ["normal", {"sigma": 0.01}]: 0.010026026
05-04 16:16:28 Initialized rpn_cls_logit_bias as bias: 0.0
05-04 16:16:28 Initialized rpn_cls_logit_weight as ["normal", {"sigma": 0.01}]: 0.010022454
05-04 16:16:28 Initialized rpn_conv_3x3_bias as bias: 0.0
05-04 16:16:29 Initialized rpn_conv_3x3_weight as ["normal", {"sigma": 0.01}]: 0.009999983
Traceback (most recent call last):
  File "detection_train.py", line 231, in <module>
    train_net(parse_args())
  File "detection_train.py", line 214, in train_net
    num_epoch=end_epoch
  File "/home/zrz/code/simpledet-master/core/detection_module.py", line 995, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/zrz/code/simpledet-master/core/detection_module.py", line 783, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced)
  File "/home/zrz/miniconda3/envs/runze_env_name/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/module/executor_group.py", line 639, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/zrz/miniconda3/envs/runze_env_name/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/metric.py", line 350, in update_dict
    metric.update_dict(labels, preds)
  File "/home/zrz/miniconda3/envs/runze_env_name/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/metric.py", line 133, in update_dict
    self.update(label, pred)
  File "/home/zrz/code/simpledet-master/core/detection_metric.py", line 41, in update
    pred_label = mx.ndarray.argmax_channel(pred).astype('int32').asnumpy().reshape(-1)
  File "/home/zrz/miniconda3/envs/runze_env_name/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/ndarray/ndarray.py", line 1995, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/zrz/miniconda3/envs/runze_env_name/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:16:32] include/mxnet/tuple.h:202: Check failed: i >= 0 && i < ndim(): index = 0 must be in range [0, -1)
Stack trace:
  [bt] (0) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x22) [0x7fd217e101d2]
  [bt] (1) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(mxnet::op::GAPOp<mshadow::gpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x5dc) [0x7fd21b550d0c]
  [bt] (2) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x4b9) [0x7fd219591629]
  [bt] (3) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x76) [0x7fd219c2dc26]
  [bt] (4) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(+0x2d4425f) [0x7fd219be825f]
  [bt] (5) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x93c) [0x7fd219b42fbc]
  [bt] (6) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0x105) [0x7fd219b5a115]
  [bt] (7) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#4}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>&&)+0x3e) [0x7fd219b5a39e]
  [bt] (8) /home/zrz/code/incubator-mxnet/lib/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run()+0x3a) [0x7fd219b414fa]

**Comment by RogerChern** [comment]
This is a known issue of Global Average Pool operator, and we have fixed it by adopting the pool op provided by MXNet in mxnext. Please update your mxnext and this should be resolved.

**Comment by runzeer** [comment]
How to update the new mxnext? I just install the mxnext using the
pip3 install 'git+https://github.com/RogerChern/mxnext.git@pkg'

any methods else for the mxnext installation

**Comment by RogerChern** [comment]
Uninstall the package with pip. And pull mxnext into your simpledet directory by `git clone https://github.com/RogerChern/mxnext`. We shall update the package later.

**Comment by runzeer** [comment]
So the package is not updated,right? When will the package be updated?

**Comment by RogerChern** [comment]
The pkg branch is not updated yet, but the master branch is already updated.
