### ISSUE TITLE
可否给一个在通过conda安装simpledet环境的安装教程

### ISSUE THREAD

**Issue by musicshmily** [TuSimple/simpledet#87]

**Comment by leiyuncong1202** [comment]
参考：https://github.com/TuSimple/simpledet
环境：Ubuntu16.04+CUDA9.0+cudnn7.0.5+Anaconda3+Python3.7
步骤：
1.创建并激活conda环境
conda create -n simpledet python=3.7
conda activate simpledet

2.安装python依赖包
sudo ~/anaconda3/bin pip install 'matplotlib<3.1' opencv-python pytz

3.安装相应版本的MXNet，wheel的具体下载地址见INSTALL.md：
sudo ~/anaconda3/bin pip install https://1dv.alarge.space/mxnet_cu90-1.6.0b20190820-py2.py3-none-manylinux1_x86_64.whl

4.安装pycocotools
sudo ~/anaconda3/bin pip install 'git+https://github.com/RogerChern/cocoapi.git#subdirectory=PythonAPI'

5.安装MXNext
sudo ~/anaconda3/bin pip install 'git+https://github.com/RogerChern/mxnext#egg=mxnext'

6.创建simpledet项目库
git clone https://github.com/tusimple/simpledet
cd simpledet
make

7.测试（若成功，则显示Faster R-CNN R-50 FPN的平均运行速度）
mkdir -p experiments/faster_r50v1_fpn_1x
python detection_infer_speed.py --config config/faster_r50v1_fpn_1x.py --shape 800 1333
