### ISSUE TITLE
val data in image_set is also part of training data?

### ISSUE THREAD

**Issue by qilicun** [TuSimple/simpledet#89]
If we specify the val dataset in *image_set* in any of the config file, ie. ``config/tridentnet_r101v2c4_c5_1x.py``,  in line 61 of ``detection_train``, it actually takes all the datasets in the *image_set* for training data?

**Comment by RogerChern** [comment]
As long as you can provide labels for your image set, you can include arbitrary datasets for training. For example, if you want to report results on coco2014minival(aka. coco2017val), you should train on coco2014train + coco2014valminusminival. Instead, if you want to report results on coco2017test-dev, you should train on coco2014train + coco2014valminusminival + coco2014 minival(aka. coco2017train + coco 2017val).
