### ISSUE TITLE
Test with one gpu!

### ISSUE THREAD

**Issue by feixiangdekaka** [TuSimple/simpledet#91]
modify  
    class KvstoreParam:
        kvstore     = "nccl"
        batch_image = General.batch_image
        gpus        = [0]
        fp16        = General.fp16

raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:49:14] include/mxnet/tuple.h:202: Check failed: i >= 0 && i < ndim(): index = 0 must be in range [0, -1)

**Comment by RogerChern** [comment]
Could you please provide the full error message.

**Comment by feixiangdekaka** [comment]
modify
class KvstoreParam:
kvstore = "nccl"
batch_image = General.batch_image
gpus = [0]
fp16 = General.fp16
I compile it  by  the  third  method.Exception in thread Thread-7:  is  the  thread problem?or  cuda problem,thank you!

(simpledet) lei@lei:~/anaconda3/envs/simpledet/simpledet$ python3 detection_test.py --config config/tridentnet_r101v2c4_c5_1x.py 
total number of images: 5000
load experiments/tridentnet_r101v2c4_c5_1x/checkpoint-0006.params
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/lei/anaconda3/envs/simpledet/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/home/lei/anaconda3/envs/simpledet/lib/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "detection_test.py", line 79, in eval_worker
    out = [x.asnumpy() for x in exe.get_outputs()]
  File "detection_test.py", line 79, in <listcomp>
    out = [x.asnumpy() for x in exe.get_outputs()]
  File "/home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1996, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:46:45] include/mxnet/tuple.h:202: Check failed: i >= 0 && i < ndim(): index = 0 must be in range [0, -1)
Stack trace:
  [bt] (0) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x34) [0x7f02aa9962f4]
  [bt] (1) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::GAPOp<mshadow::gpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x373) [0x7f02ae2f36b3]
  [bt] (2) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::OperatorState::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x2dc) [0x7f02ac24b9ec]
  [bt] (3) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x79) [0x7f02ac1a66e9]
  [bt] (4) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(+0x27a260d) [0x7f02ac16060d]
  [bt] (5) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x5c4) [0x7f02ac81b7d4]
  [bt] (6) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0x11d) [0x7f02ac8305fd]
  [bt] (7) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#4}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>)+0x4e) [0x7f02ac83089e]
  [bt] (8) /home/lei/anaconda3/envs/simpledet/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run()+0x4b) [0x7f02ac81972b]

**Comment by RogerChern** [comment]
Please refer to #83
