### ISSUE TITLE
Problem about the shape of scores feature map in cpp file

### ISSUE THREAD

**Issue by xingweiXu** [TuSimple/simpledet#94]
There is a line in "proposal_v2.cc"
`workspace_proposals[n][index][4] = scores[n][i + width * height * num_anchors][j][k];
`
Right value looks like each pixel has a score channel with the shape of width*height.

I feel it should be
`workspace_proposals[n][index][4] = scores[n][i + num_anchors][j][k];
`
@RogerChern 

PS: The same line also appears in  other "proposal*.cc" files
https://github.com/TuSimple/simpledet/blob/7d1b95901997912f10c99eb2e4b4b39ff028509e/operator_cxx/contrib/proposal_v2.cc#L381

**Comment by RogerChern** [comment]
Sorry, the cpu version of the proposal operator is just a placeholder.
