### ISSUE TITLE
The performance of Cascade R-CNN and FPN Fasetr R-CNN are lower than Faster R-CNN on the same dataset?

### ISSUE THREAD

**Issue by hdjsjyl** [TuSimple/simpledet#97]
Thanks for the excellent work, but I find one thing that the performance of Cascade R-CNN and FPN Faster R-CNN are lower than Faster R-CNN on the same dataset? Can you provide some advice about that? Any advice will be appreciated, thanks.

**Comment by xchani** [comment]
You'd better read [MODEL_ZOO](https://github.com/TuSimple/simpledet/blob/master/MODEL_ZOO.md) more carefully.
